// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protobuf/svr/platform/pkgs.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Comm.Svr.Platform.Pkgs {

  /// <summary>Holder for reflection information generated from protobuf/svr/platform/pkgs.proto</summary>
  public static partial class PkgsReflection {

    #region Descriptor
    /// <summary>File descriptor for protobuf/svr/platform/pkgs.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PkgsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBwcm90b2J1Zi9zdnIvcGxhdGZvcm0vcGtncy5wcm90bxIWY29tbS5zdnIu",
            "cGxhdGZvcm0ucGtncxokcHJvdG9idWYvYXBpL2NvbW1vbi9jb21tb24tbmV0",
            "LnByb3RvGiNwcm90b2J1Zi9tZ3IvcGxhdGZvcm0vZmVhdHVyZS5wcm90byJC",
            "Cg5HZXRQYWNrYWdlc1JlcRISCgpzb2NrcHVwcGV0GAogASgJEgsKA2FubRgL",
            "IAEoCRIPCgdzdWJfYW5tGAwgASgJIkQKDkdldFBhY2thZ2VzUnNwEjIKBHBr",
            "Z3MYCiADKAsyJC5jb21tLm1nci5wbGF0Zm9ybS5mZWF0dXJlLlBrZ09zdHlw",
            "ZTJsCgtQYWNrYWdlc1N2chJdCgtHZXRQYWNrYWdlcxImLmNvbW0uc3ZyLnBs",
            "YXRmb3JtLnBrZ3MuR2V0UGFja2FnZXNSZXEaJi5jb21tLnN2ci5wbGF0Zm9y",
            "bS5wa2dzLkdldFBhY2thZ2VzUnNwQkcKDmNvbS5wa2dzLnByb3RvWjVnaXRp",
            "dC5jYy9zb2NpYWwvcHJvdG9idWYvZ2VuY29kZS9zdnIvcGxhdGZvcm0vcGJz",
            "cGtnc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Scommon.CommonNetReflection.Descriptor, global::Comm.Mgr.Platform.Feature.FeatureReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Comm.Svr.Platform.Pkgs.GetPackagesReq), global::Comm.Svr.Platform.Pkgs.GetPackagesReq.Parser, new[]{ "Sockpuppet", "Anm", "SubAnm" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Comm.Svr.Platform.Pkgs.GetPackagesRsp), global::Comm.Svr.Platform.Pkgs.GetPackagesRsp.Parser, new[]{ "Pkgs" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetPackagesReq : pb::IMessage<GetPackagesReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetPackagesReq> _parser = new pb::MessageParser<GetPackagesReq>(() => new GetPackagesReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetPackagesReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Comm.Svr.Platform.Pkgs.PkgsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetPackagesReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetPackagesReq(GetPackagesReq other) : this() {
      sockpuppet_ = other.sockpuppet_;
      anm_ = other.anm_;
      subAnm_ = other.subAnm_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetPackagesReq Clone() {
      return new GetPackagesReq(this);
    }

    /// <summary>Field number for the "sockpuppet" field.</summary>
    public const int SockpuppetFieldNumber = 10;
    private string sockpuppet_ = "";
    /// <summary>
    /// 马甲名，如果没有，则不填
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Sockpuppet {
      get { return sockpuppet_; }
      set {
        sockpuppet_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "anm" field.</summary>
    public const int AnmFieldNumber = 11;
    private string anm_ = "";
    /// <summary>
    /// 业务名
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Anm {
      get { return anm_; }
      set {
        anm_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sub_anm" field.</summary>
    public const int SubAnmFieldNumber = 12;
    private string subAnm_ = "";
    /// <summary>
    /// 业务子代号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SubAnm {
      get { return subAnm_; }
      set {
        subAnm_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetPackagesReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetPackagesReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Sockpuppet != other.Sockpuppet) return false;
      if (Anm != other.Anm) return false;
      if (SubAnm != other.SubAnm) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Sockpuppet.Length != 0) hash ^= Sockpuppet.GetHashCode();
      if (Anm.Length != 0) hash ^= Anm.GetHashCode();
      if (SubAnm.Length != 0) hash ^= SubAnm.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Sockpuppet.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Sockpuppet);
      }
      if (Anm.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Anm);
      }
      if (SubAnm.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(SubAnm);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Sockpuppet.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Sockpuppet);
      }
      if (Anm.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Anm);
      }
      if (SubAnm.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(SubAnm);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Sockpuppet.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sockpuppet);
      }
      if (Anm.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Anm);
      }
      if (SubAnm.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SubAnm);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetPackagesReq other) {
      if (other == null) {
        return;
      }
      if (other.Sockpuppet.Length != 0) {
        Sockpuppet = other.Sockpuppet;
      }
      if (other.Anm.Length != 0) {
        Anm = other.Anm;
      }
      if (other.SubAnm.Length != 0) {
        SubAnm = other.SubAnm;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 82: {
            Sockpuppet = input.ReadString();
            break;
          }
          case 90: {
            Anm = input.ReadString();
            break;
          }
          case 98: {
            SubAnm = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 82: {
            Sockpuppet = input.ReadString();
            break;
          }
          case 90: {
            Anm = input.ReadString();
            break;
          }
          case 98: {
            SubAnm = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetPackagesRsp : pb::IMessage<GetPackagesRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetPackagesRsp> _parser = new pb::MessageParser<GetPackagesRsp>(() => new GetPackagesRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetPackagesRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Comm.Svr.Platform.Pkgs.PkgsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetPackagesRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetPackagesRsp(GetPackagesRsp other) : this() {
      pkgs_ = other.pkgs_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetPackagesRsp Clone() {
      return new GetPackagesRsp(this);
    }

    /// <summary>Field number for the "pkgs" field.</summary>
    public const int PkgsFieldNumber = 10;
    private static readonly pb::FieldCodec<global::Comm.Mgr.Platform.Feature.PkgOstype> _repeated_pkgs_codec
        = pb::FieldCodec.ForMessage(82, global::Comm.Mgr.Platform.Feature.PkgOstype.Parser);
    private readonly pbc::RepeatedField<global::Comm.Mgr.Platform.Feature.PkgOstype> pkgs_ = new pbc::RepeatedField<global::Comm.Mgr.Platform.Feature.PkgOstype>();
    /// <summary>
    /// 所有包名，包括ios和android
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Comm.Mgr.Platform.Feature.PkgOstype> Pkgs {
      get { return pkgs_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetPackagesRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetPackagesRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!pkgs_.Equals(other.pkgs_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= pkgs_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      pkgs_.WriteTo(output, _repeated_pkgs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      pkgs_.WriteTo(ref output, _repeated_pkgs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += pkgs_.CalculateSize(_repeated_pkgs_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetPackagesRsp other) {
      if (other == null) {
        return;
      }
      pkgs_.Add(other.pkgs_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 82: {
            pkgs_.AddEntriesFrom(input, _repeated_pkgs_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 82: {
            pkgs_.AddEntriesFrom(ref input, _repeated_pkgs_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
