// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protobuf/api/adapter/model.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Comm.Api.Adapter {

  /// <summary>Holder for reflection information generated from protobuf/api/adapter/model.proto</summary>
  public static partial class ModelReflection {

    #region Descriptor
    /// <summary>File descriptor for protobuf/api/adapter/model.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ModelReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBwcm90b2J1Zi9hcGkvYWRhcHRlci9tb2RlbC5wcm90bxIQY29tbS5hcGku",
            "YWRhcHRlchoicHJvdG9idWYvYXBpL3Njb25maWcvb3B0aW9ucy5wcm90bxok",
            "cHJvdG9idWYvYXBpL2NvbW1vbi9jb21tb24tbmV0LnByb3RvGiJwcm90b2J1",
            "Zi9hcGkvYWNjb3VudC9hY2NvdW50LnByb3RvInAKB1Jvb21UYWcSCgoCaWQY",
            "ASABKAMSLQoFc3R5bGUYAiABKA4yHi5jb21tLmFwaS5hZGFwdGVyLlJvb21U",
            "YWdTdHlsZRIOCgZ3ZWlnaHQYAyABKAUSDAoEbmFtZRgUIAEoCRIMCgRpY29u",
            "GB4gASgJItgCCghVc2VySW5mbxILCgN1aWQYASABKAMSEAoIc2hvd191aWQY",
            "AiABKAkSEAoIbmlja25hbWUYAyABKAkSDgoGYXZhdGFyGAQgASgJEhUKDXJl",
            "Z2lzdGVyZWRfYXQYBSABKAMSHwoGZ2VuZGVyGAYgASgOMg8uc2NvbW1vbi5H",
            "ZW5kZXISLAoMY291bnRyeV9pbmZvGAcgASgLMhYucGJhY2NvdW50LkNvdW50",
            "cnlJbmZvEiwKBnN0YXR1cxgUIAEoDjIcLmNvbW0uYXBpLmFkYXB0ZXIuVXNl",
            "clN0YXR1cxIQCghiaXJ0aGRheRgeIAEoCRILCgNhZ2UYHyABKAUSFAoMaW50",
            "cm9kdWN0aW9uGCggASgJEgwKBGNpdHkYMiABKAkSEAoIbGFuZ3VhZ2UYZCAB",
            "KAkSDwoHYml6X2V4dBhuIAEoDBIRCglzY2VuZV9leHQYbyABKAwqwwEKDkZh",
            "bWlseVJvbGVUeXBlEhkKFUZBTUlMWV9ST0xFX1RZUEVfTk9ORRAAEh4KGkZB",
            "TUlMWV9ST0xFX1RZUEVfUEFUUklBUkNIEAESIwofRkFNSUxZX1JPTEVfVFlQ",
            "RV9WSUNFX1BBVFJJQVJDSBACEhoKFkZBTUlMWV9ST0xFX1RZUEVfRUxERVIQ",
            "AxIaChZGQU1JTFlfUk9MRV9UWVBFX0FETUlOEAQSGQoVRkFNSUxZX1JPTEVf",
            "VFlQRV9NQVNTEGMqZgoKUm9vbVN0YXR1cxIUChBST09NX1NUQVRVU19OT05F",
            "EAASFgoSUk9PTV9TVEFUVVNfTElWSU5HEAESFQoRUk9PTV9TVEFUVVNfQ0xP",
            "U0UQAhITCg9ST09NX1NUQVRVU19CQU4QAyq/AQoNRm9sbG93RXJyQ29kZRIY",
            "ChRGT0xMT1dfRVJSX0NPREVfTk9ORRAAEhsKF0ZPTExPV19FUlJfQ09ERV9C",
            "TE9DS0VEEAESHwobRk9MTE9XX0VSUl9DT0RFX1JFQUNIX0xJTUlUEAISGAoU",
            "Rk9MTE9XX0VSUl9DT0RFX1JJU0sQAxIhCh1GT0xMT1dfRVJSX0NPREVfQkxP",
            "Q0tfQllfU0VMRhAEEhkKFUZPTExPV19FUlJfQ09ERV9PVEhFUhBkKtMBChBS",
            "ZXdhcmRTb3VyY2VUeXBlEhsKF1JFV0FSRF9TT1VSQ0VfVFlQRV9OT05FEAAS",
            "GwoXUkVXQVJEX1NPVVJDRV9UWVBFX1JBTksQARIbChdSRVdBUkRfU09VUkNF",
            "X1RZUEVfVEFTSxACEh4KGlJFV0FSRF9TT1VSQ0VfVFlQRV9MT1RURVJZEAMS",
            "IAocUkVXQVJEX1NPVVJDRV9UWVBFX1BSSVpFUE9PTBAEEiYKIlJFV0FSRF9T",
            "T1VSQ0VfVFlQRV9QT0lOVFNfRVhDSEFOR0UQBSqRAgoIQ3VycmVuY3kSEQoN",
            "Q1VSUkVOQ1lfTk9ORRAAEhcKE0NVUlJFTkNZX1NFVFRMRU1FTlQQARIYChRD",
            "VVJSRU5DWV9DT05TVU1QVElPThACEhgKFENVUlJFTkNZX0NPSU5fQUdFTkNZ",
            "EAMSGAoUQ1VSUkVOQ1lfRE9MTEFSX0NFTlQQBBIbChdDVVJSRU5DWV9DT0lO",
            "X09QRVJBVElORxAFEhIKDkNVUlJFTkNZX1BPSU5UEAYSEwoPQ1VSUkVOQ1lf",
            "QUNUSVZFEAcSIgoeQ1VSUkVOQ1lfU0VDT05EQVJZX0NPTlNVTVBUSU9OEAwS",
            "IQodQ1VSUkVOQ1lfU0VDT05EQVJZX1NFVFRMRU1FTlQQDSpbCgxSb29tVGFn",
            "U3R5bGUSFgoSUk9PTV9UQUdfVFlQRV9OT05FEAASFgoSUk9PTV9UQUdfVFlQ",
            "RV9JQ09OEAoSGwoXUk9PTV9UQUdfVFlQRV9JQ09OX05BTUUQFCo7CgtTdWJq",
            "ZWN0VHlwZRIVChFTVUJKRUNUX1RZUEVfTk9ORRAAEhUKEVNVQkpFQ1RfVFlQ",
            "RV9VU0VSEAoqmQEKClVzZXJTdGF0dXMSFAoQVVNFUl9TVEFUVVNfTk9ORRAA",
            "EhYKElVTRVJfU1RBVFVTX05PUk1BTBABEhMKD1VTRVJfU1RBVFVTX0JBThAC",
            "EhYKElVTRVJfU1RBVFVTX0ZST1pFThADEhgKFFVTRVJfU1RBVFVTX1dJVEhE",
            "UkFXEAQSFgoSVVNFUl9TVEFUVVNfREVMRVRFEAUqzQIKFFJhbmtSZXdhcmRU",
            "YXJnZXRUeXBlEiAKHFJBTktfUkVXQVJEX1RBUkdFVF9UWVBFX05PTkUQABIt",
            "ChxSQU5LX1JFV0FSRF9UQVJHRVRfVFlQRV9VU0VSEAEaC6qCm00GCgRVc2Vy",
            "Ej4KJVJBTktfUkVXQVJEX1RBUkdFVF9UWVBFX1VTRVJfUkVTT1VSQ0UQAhoT",
            "qoKbTQ4KDFVzZXJSZXNvdXJjZRIxCh5SQU5LX1JFV0FSRF9UQVJHRVRfVFlQ",
            "RV9GQU1JTFkQBRoNqoKbTQgKBkZhbWlseRJCCidSQU5LX1JFV0FSRF9UQVJH",
            "RVRfVFlQRV9GQU1JTFlfUkVTT1VSQ0UQBhoVqoKbTRAKDkZhbWlseVJlc291",
            "cmNlEi0KHFJBTktfUkVXQVJEX1RBUkdFVF9UWVBFX1JPT00QBxoLqoKbTQYK",
            "BFJvb20qLAoDWW9OEgwKCFlPTl9OT05FEAASCwoHWU9OX1lFUxABEgoKBllP",
            "Tl9OTxACKngKDFVzZXJJZGVudGl0eRIWChJVU0VSX0lERU5USVRZX05PTkUQ",
            "ABIWChJVU0VSX0lERU5USVRZX1VTRVIQChIYChRVU0VSX0lERU5USVRZX0FO",
            "Q0hPUhAUEh4KGlVTRVJfSURFTlRJVFlfVU5DTEFTU0lGSUVEEGQqTQoGSURU",
            "eXBlEhAKDElEX1RZUEVfTk9ORRAAEg8KC0lEX1RZUEVfVUlEEAoSDwoLSURf",
            "VFlQRV9SSUQQFBIPCgtJRF9UWVBFX0ZJRBAeQmUKImNvbS5lbnRlcnRhaW4u",
            "c25zLmNvbW0uYXBpLmFkYXB0ZXJaLmdpdGl0LmNjL3NvY2lhbC9wcm90b2J1",
            "Zi9nZW5jb2RlL2FwaS9wYmFkYXB0ZXK6Ag5Db21tQXBpQWRhcHRlcmIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Sconfig.Schema.OptionsReflection.Descriptor, global::Scommon.CommonNetReflection.Descriptor, global::Pbaccount.AccountReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Comm.Api.Adapter.FamilyRoleType), typeof(global::Comm.Api.Adapter.RoomStatus), typeof(global::Comm.Api.Adapter.FollowErrCode), typeof(global::Comm.Api.Adapter.RewardSourceType), typeof(global::Comm.Api.Adapter.Currency), typeof(global::Comm.Api.Adapter.RoomTagStyle), typeof(global::Comm.Api.Adapter.SubjectType), typeof(global::Comm.Api.Adapter.UserStatus), typeof(global::Comm.Api.Adapter.RankRewardTargetType), typeof(global::Comm.Api.Adapter.YoN), typeof(global::Comm.Api.Adapter.UserIdentity), typeof(global::Comm.Api.Adapter.IDType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Comm.Api.Adapter.RoomTag), global::Comm.Api.Adapter.RoomTag.Parser, new[]{ "Id", "Style", "Weight", "Name", "Icon" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Comm.Api.Adapter.UserInfo), global::Comm.Api.Adapter.UserInfo.Parser, new[]{ "Uid", "ShowUid", "Nickname", "Avatar", "RegisteredAt", "Gender", "CountryInfo", "Status", "Birthday", "Age", "Introduction", "City", "Language", "BizExt", "SceneExt" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 家族角色类型
  /// </summary>
  public enum FamilyRoleType {
    /// <summary>
    /// 非家族成员
    /// </summary>
    [pbr::OriginalName("FAMILY_ROLE_TYPE_NONE")] None = 0,
    /// <summary>
    /// 家族长
    /// </summary>
    [pbr::OriginalName("FAMILY_ROLE_TYPE_PATRIARCH")] Patriarch = 1,
    /// <summary>
    /// 副家族长
    /// </summary>
    [pbr::OriginalName("FAMILY_ROLE_TYPE_VICE_PATRIARCH")] VicePatriarch = 2,
    /// <summary>
    /// 长老, 对应echo 的大佬
    /// </summary>
    [pbr::OriginalName("FAMILY_ROLE_TYPE_ELDER")] Elder = 3,
    /// <summary>
    /// 管理员
    /// </summary>
    [pbr::OriginalName("FAMILY_ROLE_TYPE_ADMIN")] Admin = 4,
    /// <summary>
    /// 普通成员
    /// </summary>
    [pbr::OriginalName("FAMILY_ROLE_TYPE_MASS")] Mass = 99,
  }

  public enum RoomStatus {
    [pbr::OriginalName("ROOM_STATUS_NONE")] None = 0,
    /// <summary>
    /// 直播中
    /// </summary>
    [pbr::OriginalName("ROOM_STATUS_LIVING")] Living = 1,
    /// <summary>
    /// 下播中
    /// </summary>
    [pbr::OriginalName("ROOM_STATUS_CLOSE")] Close = 2,
    /// <summary>
    /// 封禁
    /// </summary>
    [pbr::OriginalName("ROOM_STATUS_BAN")] Ban = 3,
  }

  public enum FollowErrCode {
    [pbr::OriginalName("FOLLOW_ERR_CODE_NONE")] None = 0,
    /// <summary>
    /// 被对方拉黑
    /// </summary>
    [pbr::OriginalName("FOLLOW_ERR_CODE_BLOCKED")] Blocked = 1,
    /// <summary>
    /// 到达关注人数上限
    /// </summary>
    [pbr::OriginalName("FOLLOW_ERR_CODE_REACH_LIMIT")] ReachLimit = 2,
    /// <summary>
    /// 被风控了
    /// </summary>
    [pbr::OriginalName("FOLLOW_ERR_CODE_RISK")] Risk = 3,
    /// <summary>
    /// 主动拉黑
    /// </summary>
    [pbr::OriginalName("FOLLOW_ERR_CODE_BLOCK_BY_SELF")] BlockBySelf = 4,
    /// <summary>
    /// 其他错误
    /// </summary>
    [pbr::OriginalName("FOLLOW_ERR_CODE_OTHER")] Other = 100,
  }

  public enum RewardSourceType {
    [pbr::OriginalName("REWARD_SOURCE_TYPE_NONE")] None = 0,
    /// <summary>
    /// 榜单
    /// </summary>
    [pbr::OriginalName("REWARD_SOURCE_TYPE_RANK")] Rank = 1,
    /// <summary>
    /// 任务
    /// </summary>
    [pbr::OriginalName("REWARD_SOURCE_TYPE_TASK")] Task = 2,
    /// <summary>
    /// 抽奖
    /// </summary>
    [pbr::OriginalName("REWARD_SOURCE_TYPE_LOTTERY")] Lottery = 3,
    /// <summary>
    /// 奖池
    /// </summary>
    [pbr::OriginalName("REWARD_SOURCE_TYPE_PRIZEPOOL")] Prizepool = 4,
    /// <summary>
    /// 积分兑换
    /// </summary>
    [pbr::OriginalName("REWARD_SOURCE_TYPE_POINTS_EXCHANGE")] PointsExchange = 5,
  }

  /// <summary>
  ///
  ///因为不同业务的货币叫法不一致, 但概念是相通的:
  ///Playmate:
  ///结算: 钻石-diamond
  ///消费: 星币-star
  ///币商: 星票-ticket
  ///美分: 美分-usd
  ///
  ///Lucky:
  ///结算: 积分-point
  ///消费: 金币-coin
  ///币商: -
  ///美分: -
  ///
  ///Echo:
  ///结算: 钻石-diamond
  ///消费: 金币-coin
  ///币商: 金票-ticket
  ///美分: 美分-usd
  ///
  ///HalaMe:
  ///结算: 宝石-gems
  ///消费: 钻石-diamond
  ///币商: 金票-ticket
  ///美分: 美分-usd
  ///
  ///Carne:
  ///经营货币：coin
  ///
  ///darling:
  ///结算：金币
  ///消费：金币
  ///
  ///dating:
  ///结算：金币
  ///消费：宝石
  ///促活：银豆
  ///
  ///nova：
  ///消费：钻石
  ///第二消费货币：金币
  ///
  ///所以公会中台对货币进行以下抽象, 让业务各自去对应自己的货币类型.
  /// </summary>
  public enum Currency {
    [pbr::OriginalName("CURRENCY_NONE")] None = 0,
    /// <summary>
    /// 结算货币
    /// </summary>
    [pbr::OriginalName("CURRENCY_SETTLEMENT")] Settlement = 1,
    /// <summary>
    /// 消费货币
    /// </summary>
    [pbr::OriginalName("CURRENCY_CONSUMPTION")] Consumption = 2,
    /// <summary>
    /// 币商货币
    /// </summary>
    [pbr::OriginalName("CURRENCY_COIN_AGENCY")] CoinAgency = 3,
    /// <summary>
    /// 美分货币
    /// </summary>
    [pbr::OriginalName("CURRENCY_DOLLAR_CENT")] DollarCent = 4,
    /// <summary>
    /// 经营货币
    /// </summary>
    [pbr::OriginalName("CURRENCY_COIN_OPERATING")] CoinOperating = 5,
    /// <summary>
    /// 积分货币，一般是做任务获得的积分，目前只有dating 用
    /// </summary>
    [pbr::OriginalName("CURRENCY_POINT")] Point = 6,
    /// <summary>
    /// 促活货币，目前只有dating 用
    /// </summary>
    [pbr::OriginalName("CURRENCY_ACTIVE")] Active = 7,
    /// <summary>
    /// 第二消费货币
    /// </summary>
    [pbr::OriginalName("CURRENCY_SECONDARY_CONSUMPTION")] SecondaryConsumption = 12,
    /// <summary>
    /// 第二结算货币， 目前只有dating 用来做用户收益结算
    /// </summary>
    [pbr::OriginalName("CURRENCY_SECONDARY_SETTLEMENT")] SecondarySettlement = 13,
  }

  /// <summary>
  /// 房间标签模式
  /// </summary>
  public enum RoomTagStyle {
    [pbr::OriginalName("ROOM_TAG_TYPE_NONE")] RoomTagTypeNone = 0,
    /// <summary>
    /// 仅展示图标
    /// </summary>
    [pbr::OriginalName("ROOM_TAG_TYPE_ICON")] RoomTagTypeIcon = 10,
    /// <summary>
    /// 展示图标 + 名字
    /// </summary>
    [pbr::OriginalName("ROOM_TAG_TYPE_ICON_NAME")] RoomTagTypeIconName = 20,
  }

  /// <summary>
  /// 主体类型
  /// </summary>
  public enum SubjectType {
    /// <summary>
    /// 无意义
    /// </summary>
    [pbr::OriginalName("SUBJECT_TYPE_NONE")] None = 0,
    /// <summary>
    /// 用户
    /// </summary>
    [pbr::OriginalName("SUBJECT_TYPE_USER")] User = 10,
  }

  /// <summary>
  /// 用户状态
  /// </summary>
  public enum UserStatus {
    /// <summary>
    /// 无状态
    /// </summary>
    [pbr::OriginalName("USER_STATUS_NONE")] None = 0,
    /// <summary>
    /// 正常
    /// </summary>
    [pbr::OriginalName("USER_STATUS_NORMAL")] Normal = 1,
    /// <summary>
    /// 封禁
    /// </summary>
    [pbr::OriginalName("USER_STATUS_BAN")] Ban = 2,
    /// <summary>
    /// 冻结
    /// </summary>
    [pbr::OriginalName("USER_STATUS_FROZEN")] Frozen = 3,
    /// <summary>
    /// 注销（注销冷静期过后更新为删除）
    /// </summary>
    [pbr::OriginalName("USER_STATUS_WITHDRAW")] Withdraw = 4,
    /// <summary>
    /// 删除
    /// </summary>
    [pbr::OriginalName("USER_STATUS_DELETE")] Delete = 5,
  }

  /// <summary>
  /// 榜单奖励目标类型
  /// </summary>
  public enum RankRewardTargetType {
    [pbr::OriginalName("RANK_REWARD_TARGET_TYPE_NONE")] None = 0,
    /// <summary>
    /// 用户
    /// </summary>
    [pbr::OriginalName("RANK_REWARD_TARGET_TYPE_USER")] User = 1,
    /// <summary>
    /// 用户资源
    /// </summary>
    [pbr::OriginalName("RANK_REWARD_TARGET_TYPE_USER_RESOURCE")] UserResource = 2,
    /// <summary>
    /// 家族
    /// </summary>
    [pbr::OriginalName("RANK_REWARD_TARGET_TYPE_FAMILY")] Family = 5,
    /// <summary>
    /// 家族资源
    /// </summary>
    [pbr::OriginalName("RANK_REWARD_TARGET_TYPE_FAMILY_RESOURCE")] FamilyResource = 6,
    /// <summary>
    /// 房间
    /// </summary>
    [pbr::OriginalName("RANK_REWARD_TARGET_TYPE_ROOM")] Room = 7,
  }

  /// <summary>
  /// Yes or No, 有些场景直接用 bool 类型无法表达"不限制"这个选项, 所以加上这个枚举.
  /// </summary>
  public enum YoN {
    /// <summary>
    /// 未指定/不限制
    /// </summary>
    [pbr::OriginalName("YON_NONE")] None = 0,
    /// <summary>
    /// 是
    /// </summary>
    [pbr::OriginalName("YON_YES")] Yes = 1,
    /// <summary>
    /// 否
    /// </summary>
    [pbr::OriginalName("YON_NO")] No = 2,
  }

  /// <summary>
  /// 用户身份
  /// </summary>
  public enum UserIdentity {
    /// <summary>
    /// 不存在
    /// </summary>
    [pbr::OriginalName("USER_IDENTITY_NONE")] None = 0,
    /// <summary>
    /// 用户
    /// </summary>
    [pbr::OriginalName("USER_IDENTITY_USER")] User = 10,
    /// <summary>
    /// 主播
    /// </summary>
    [pbr::OriginalName("USER_IDENTITY_ANCHOR")] Anchor = 20,
    /// <summary>
    /// 未分类, 即用户存在但身份不在上述已定义的之中.
    /// </summary>
    [pbr::OriginalName("USER_IDENTITY_UNCLASSIFIED")] Unclassified = 100,
  }

  /// <summary>
  /// ID类型
  /// </summary>
  public enum IDType {
    [pbr::OriginalName("ID_TYPE_NONE")] None = 0,
    /// <summary>
    /// 用户ID
    /// </summary>
    [pbr::OriginalName("ID_TYPE_UID")] Uid = 10,
    /// <summary>
    /// 房间ID
    /// </summary>
    [pbr::OriginalName("ID_TYPE_RID")] Rid = 20,
    /// <summary>
    /// 家族ID
    /// </summary>
    [pbr::OriginalName("ID_TYPE_FID")] Fid = 30,
  }

  #endregion

  #region Messages
  /// <summary>
  /// 房间标签
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RoomTag : pb::IMessage<RoomTag>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RoomTag> _parser = new pb::MessageParser<RoomTag>(() => new RoomTag());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RoomTag> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Comm.Api.Adapter.ModelReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoomTag() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoomTag(RoomTag other) : this() {
      id_ = other.id_;
      style_ = other.style_;
      weight_ = other.weight_;
      name_ = other.name_;
      icon_ = other.icon_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoomTag Clone() {
      return new RoomTag(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    /// <summary>
    /// 标签
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "style" field.</summary>
    public const int StyleFieldNumber = 2;
    private global::Comm.Api.Adapter.RoomTagStyle style_ = global::Comm.Api.Adapter.RoomTagStyle.RoomTagTypeNone;
    /// <summary>
    /// 房间标签模式
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Comm.Api.Adapter.RoomTagStyle Style {
      get { return style_; }
      set {
        style_ = value;
      }
    }

    /// <summary>Field number for the "weight" field.</summary>
    public const int WeightFieldNumber = 3;
    private int weight_;
    /// <summary>
    /// 标签权重, 如果一个房间有多个标签时按权重从高到低排序和剔除显示不下的.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Weight {
      get { return weight_; }
      set {
        weight_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 20;
    private string name_ = "";
    /// <summary>
    /// 标签名称内容
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "icon" field.</summary>
    public const int IconFieldNumber = 30;
    private string icon_ = "";
    /// <summary>
    /// 标签图标
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Icon {
      get { return icon_; }
      set {
        icon_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RoomTag);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RoomTag other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Style != other.Style) return false;
      if (Weight != other.Weight) return false;
      if (Name != other.Name) return false;
      if (Icon != other.Icon) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Style != global::Comm.Api.Adapter.RoomTagStyle.RoomTagTypeNone) hash ^= Style.GetHashCode();
      if (Weight != 0) hash ^= Weight.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Icon.Length != 0) hash ^= Icon.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Style != global::Comm.Api.Adapter.RoomTagStyle.RoomTagTypeNone) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Style);
      }
      if (Weight != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Weight);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(162, 1);
        output.WriteString(Name);
      }
      if (Icon.Length != 0) {
        output.WriteRawTag(242, 1);
        output.WriteString(Icon);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Style != global::Comm.Api.Adapter.RoomTagStyle.RoomTagTypeNone) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Style);
      }
      if (Weight != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Weight);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(162, 1);
        output.WriteString(Name);
      }
      if (Icon.Length != 0) {
        output.WriteRawTag(242, 1);
        output.WriteString(Icon);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (Style != global::Comm.Api.Adapter.RoomTagStyle.RoomTagTypeNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Style);
      }
      if (Weight != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Weight);
      }
      if (Name.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Icon.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Icon);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RoomTag other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Style != global::Comm.Api.Adapter.RoomTagStyle.RoomTagTypeNone) {
        Style = other.Style;
      }
      if (other.Weight != 0) {
        Weight = other.Weight;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Icon.Length != 0) {
        Icon = other.Icon;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            Style = (global::Comm.Api.Adapter.RoomTagStyle) input.ReadEnum();
            break;
          }
          case 24: {
            Weight = input.ReadInt32();
            break;
          }
          case 162: {
            Name = input.ReadString();
            break;
          }
          case 242: {
            Icon = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            Style = (global::Comm.Api.Adapter.RoomTagStyle) input.ReadEnum();
            break;
          }
          case 24: {
            Weight = input.ReadInt32();
            break;
          }
          case 162: {
            Name = input.ReadString();
            break;
          }
          case 242: {
            Icon = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 用户信息, 这个是基础用户信息, 里面应当只包含通用的静态的用户信息, 而用户的某些状态或者其他动态的信息通过拓展字段来实现.
  /// 拓展信息分两种: 
  /// 1. 业务拓展信息 biz_ext, 这种是中台透传业务特有的用户信息, 通常情况下中台的接口需要提供一个 int32 数组类型的参数字段用于接收客户端需要的业务拓展用户信息类型, 
  ///    并且查询业务拓展用户信息时带给业务后端, 最后将返回值透传给客户端. 业务需要定义一个唯一的 &lt;UserInfoExt 结构体> 和 &lt;业务拓展用户信息类型枚举> 来对应 UserInfoExt 的字段.
  /// 2. 场景拓展信息 scene_ext, 例如活动中台的榜单页面返回用户是否已关注这种用 scene_ext 来承接, 客户端/前端需要用对应的结构体来解析.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UserInfo : pb::IMessage<UserInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UserInfo> _parser = new pb::MessageParser<UserInfo>(() => new UserInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UserInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Comm.Api.Adapter.ModelReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserInfo(UserInfo other) : this() {
      uid_ = other.uid_;
      showUid_ = other.showUid_;
      nickname_ = other.nickname_;
      avatar_ = other.avatar_;
      registeredAt_ = other.registeredAt_;
      gender_ = other.gender_;
      countryInfo_ = other.countryInfo_ != null ? other.countryInfo_.Clone() : null;
      status_ = other.status_;
      birthday_ = other.birthday_;
      age_ = other.age_;
      introduction_ = other.introduction_;
      city_ = other.city_;
      language_ = other.language_;
      bizExt_ = other.bizExt_;
      sceneExt_ = other.sceneExt_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserInfo Clone() {
      return new UserInfo(this);
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 1;
    private long uid_;
    /// <summary>
    /// uid
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Uid {
      get { return uid_; }
      set {
        uid_ = value;
      }
    }

    /// <summary>Field number for the "show_uid" field.</summary>
    public const int ShowUidFieldNumber = 2;
    private string showUid_ = "";
    /// <summary>
    /// show_uid
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ShowUid {
      get { return showUid_; }
      set {
        showUid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nickname" field.</summary>
    public const int NicknameFieldNumber = 3;
    private string nickname_ = "";
    /// <summary>
    /// 昵称
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nickname {
      get { return nickname_; }
      set {
        nickname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "avatar" field.</summary>
    public const int AvatarFieldNumber = 4;
    private string avatar_ = "";
    /// <summary>
    /// 头像
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Avatar {
      get { return avatar_; }
      set {
        avatar_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "registered_at" field.</summary>
    public const int RegisteredAtFieldNumber = 5;
    private long registeredAt_;
    /// <summary>
    /// 注册时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long RegisteredAt {
      get { return registeredAt_; }
      set {
        registeredAt_ = value;
      }
    }

    /// <summary>Field number for the "gender" field.</summary>
    public const int GenderFieldNumber = 6;
    private global::Scommon.Gender gender_ = global::Scommon.Gender.None;
    /// <summary>
    /// 性别
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Scommon.Gender Gender {
      get { return gender_; }
      set {
        gender_ = value;
      }
    }

    /// <summary>Field number for the "country_info" field.</summary>
    public const int CountryInfoFieldNumber = 7;
    private global::Pbaccount.CountryInfo countryInfo_;
    /// <summary>
    /// 国家信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pbaccount.CountryInfo CountryInfo {
      get { return countryInfo_; }
      set {
        countryInfo_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 20;
    private global::Comm.Api.Adapter.UserStatus status_ = global::Comm.Api.Adapter.UserStatus.None;
    /// <summary>
    /// 用户状态
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Comm.Api.Adapter.UserStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "birthday" field.</summary>
    public const int BirthdayFieldNumber = 30;
    private string birthday_ = "";
    /// <summary>
    /// 生日 yyyy-MM-dd
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Birthday {
      get { return birthday_; }
      set {
        birthday_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "age" field.</summary>
    public const int AgeFieldNumber = 31;
    private int age_;
    /// <summary>
    /// 年龄
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Age {
      get { return age_; }
      set {
        age_ = value;
      }
    }

    /// <summary>Field number for the "introduction" field.</summary>
    public const int IntroductionFieldNumber = 40;
    private string introduction_ = "";
    /// <summary>
    /// 个人介绍
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Introduction {
      get { return introduction_; }
      set {
        introduction_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "city" field.</summary>
    public const int CityFieldNumber = 50;
    private string city_ = "";
    /// <summary>
    /// 城市
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string City {
      get { return city_; }
      set {
        city_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "language" field.</summary>
    public const int LanguageFieldNumber = 100;
    private string language_ = "";
    /// <summary>
    /// 语言码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Language {
      get { return language_; }
      set {
        language_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "biz_ext" field.</summary>
    public const int BizExtFieldNumber = 110;
    private pb::ByteString bizExt_ = pb::ByteString.Empty;
    /// <summary>
    /// 业务拓展信息, 用于透传业务拓展信息,
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString BizExt {
      get { return bizExt_; }
      set {
        bizExt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "scene_ext" field.</summary>
    public const int SceneExtFieldNumber = 111;
    private pb::ByteString sceneExt_ = pb::ByteString.Empty;
    /// <summary>
    /// 场景拓展信息, 用于中台针对不同场景拓展的用户信息.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString SceneExt {
      get { return sceneExt_; }
      set {
        sceneExt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UserInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UserInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uid != other.Uid) return false;
      if (ShowUid != other.ShowUid) return false;
      if (Nickname != other.Nickname) return false;
      if (Avatar != other.Avatar) return false;
      if (RegisteredAt != other.RegisteredAt) return false;
      if (Gender != other.Gender) return false;
      if (!object.Equals(CountryInfo, other.CountryInfo)) return false;
      if (Status != other.Status) return false;
      if (Birthday != other.Birthday) return false;
      if (Age != other.Age) return false;
      if (Introduction != other.Introduction) return false;
      if (City != other.City) return false;
      if (Language != other.Language) return false;
      if (BizExt != other.BizExt) return false;
      if (SceneExt != other.SceneExt) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Uid != 0L) hash ^= Uid.GetHashCode();
      if (ShowUid.Length != 0) hash ^= ShowUid.GetHashCode();
      if (Nickname.Length != 0) hash ^= Nickname.GetHashCode();
      if (Avatar.Length != 0) hash ^= Avatar.GetHashCode();
      if (RegisteredAt != 0L) hash ^= RegisteredAt.GetHashCode();
      if (Gender != global::Scommon.Gender.None) hash ^= Gender.GetHashCode();
      if (countryInfo_ != null) hash ^= CountryInfo.GetHashCode();
      if (Status != global::Comm.Api.Adapter.UserStatus.None) hash ^= Status.GetHashCode();
      if (Birthday.Length != 0) hash ^= Birthday.GetHashCode();
      if (Age != 0) hash ^= Age.GetHashCode();
      if (Introduction.Length != 0) hash ^= Introduction.GetHashCode();
      if (City.Length != 0) hash ^= City.GetHashCode();
      if (Language.Length != 0) hash ^= Language.GetHashCode();
      if (BizExt.Length != 0) hash ^= BizExt.GetHashCode();
      if (SceneExt.Length != 0) hash ^= SceneExt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Uid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Uid);
      }
      if (ShowUid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ShowUid);
      }
      if (Nickname.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Nickname);
      }
      if (Avatar.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Avatar);
      }
      if (RegisteredAt != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(RegisteredAt);
      }
      if (Gender != global::Scommon.Gender.None) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Gender);
      }
      if (countryInfo_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(CountryInfo);
      }
      if (Status != global::Comm.Api.Adapter.UserStatus.None) {
        output.WriteRawTag(160, 1);
        output.WriteEnum((int) Status);
      }
      if (Birthday.Length != 0) {
        output.WriteRawTag(242, 1);
        output.WriteString(Birthday);
      }
      if (Age != 0) {
        output.WriteRawTag(248, 1);
        output.WriteInt32(Age);
      }
      if (Introduction.Length != 0) {
        output.WriteRawTag(194, 2);
        output.WriteString(Introduction);
      }
      if (City.Length != 0) {
        output.WriteRawTag(146, 3);
        output.WriteString(City);
      }
      if (Language.Length != 0) {
        output.WriteRawTag(162, 6);
        output.WriteString(Language);
      }
      if (BizExt.Length != 0) {
        output.WriteRawTag(242, 6);
        output.WriteBytes(BizExt);
      }
      if (SceneExt.Length != 0) {
        output.WriteRawTag(250, 6);
        output.WriteBytes(SceneExt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Uid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Uid);
      }
      if (ShowUid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ShowUid);
      }
      if (Nickname.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Nickname);
      }
      if (Avatar.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Avatar);
      }
      if (RegisteredAt != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(RegisteredAt);
      }
      if (Gender != global::Scommon.Gender.None) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Gender);
      }
      if (countryInfo_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(CountryInfo);
      }
      if (Status != global::Comm.Api.Adapter.UserStatus.None) {
        output.WriteRawTag(160, 1);
        output.WriteEnum((int) Status);
      }
      if (Birthday.Length != 0) {
        output.WriteRawTag(242, 1);
        output.WriteString(Birthday);
      }
      if (Age != 0) {
        output.WriteRawTag(248, 1);
        output.WriteInt32(Age);
      }
      if (Introduction.Length != 0) {
        output.WriteRawTag(194, 2);
        output.WriteString(Introduction);
      }
      if (City.Length != 0) {
        output.WriteRawTag(146, 3);
        output.WriteString(City);
      }
      if (Language.Length != 0) {
        output.WriteRawTag(162, 6);
        output.WriteString(Language);
      }
      if (BizExt.Length != 0) {
        output.WriteRawTag(242, 6);
        output.WriteBytes(BizExt);
      }
      if (SceneExt.Length != 0) {
        output.WriteRawTag(250, 6);
        output.WriteBytes(SceneExt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Uid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Uid);
      }
      if (ShowUid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ShowUid);
      }
      if (Nickname.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nickname);
      }
      if (Avatar.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Avatar);
      }
      if (RegisteredAt != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(RegisteredAt);
      }
      if (Gender != global::Scommon.Gender.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Gender);
      }
      if (countryInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CountryInfo);
      }
      if (Status != global::Comm.Api.Adapter.UserStatus.None) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (Birthday.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Birthday);
      }
      if (Age != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Age);
      }
      if (Introduction.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Introduction);
      }
      if (City.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(City);
      }
      if (Language.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Language);
      }
      if (BizExt.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeBytesSize(BizExt);
      }
      if (SceneExt.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeBytesSize(SceneExt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UserInfo other) {
      if (other == null) {
        return;
      }
      if (other.Uid != 0L) {
        Uid = other.Uid;
      }
      if (other.ShowUid.Length != 0) {
        ShowUid = other.ShowUid;
      }
      if (other.Nickname.Length != 0) {
        Nickname = other.Nickname;
      }
      if (other.Avatar.Length != 0) {
        Avatar = other.Avatar;
      }
      if (other.RegisteredAt != 0L) {
        RegisteredAt = other.RegisteredAt;
      }
      if (other.Gender != global::Scommon.Gender.None) {
        Gender = other.Gender;
      }
      if (other.countryInfo_ != null) {
        if (countryInfo_ == null) {
          CountryInfo = new global::Pbaccount.CountryInfo();
        }
        CountryInfo.MergeFrom(other.CountryInfo);
      }
      if (other.Status != global::Comm.Api.Adapter.UserStatus.None) {
        Status = other.Status;
      }
      if (other.Birthday.Length != 0) {
        Birthday = other.Birthday;
      }
      if (other.Age != 0) {
        Age = other.Age;
      }
      if (other.Introduction.Length != 0) {
        Introduction = other.Introduction;
      }
      if (other.City.Length != 0) {
        City = other.City;
      }
      if (other.Language.Length != 0) {
        Language = other.Language;
      }
      if (other.BizExt.Length != 0) {
        BizExt = other.BizExt;
      }
      if (other.SceneExt.Length != 0) {
        SceneExt = other.SceneExt;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Uid = input.ReadInt64();
            break;
          }
          case 18: {
            ShowUid = input.ReadString();
            break;
          }
          case 26: {
            Nickname = input.ReadString();
            break;
          }
          case 34: {
            Avatar = input.ReadString();
            break;
          }
          case 40: {
            RegisteredAt = input.ReadInt64();
            break;
          }
          case 48: {
            Gender = (global::Scommon.Gender) input.ReadEnum();
            break;
          }
          case 58: {
            if (countryInfo_ == null) {
              CountryInfo = new global::Pbaccount.CountryInfo();
            }
            input.ReadMessage(CountryInfo);
            break;
          }
          case 160: {
            Status = (global::Comm.Api.Adapter.UserStatus) input.ReadEnum();
            break;
          }
          case 242: {
            Birthday = input.ReadString();
            break;
          }
          case 248: {
            Age = input.ReadInt32();
            break;
          }
          case 322: {
            Introduction = input.ReadString();
            break;
          }
          case 402: {
            City = input.ReadString();
            break;
          }
          case 802: {
            Language = input.ReadString();
            break;
          }
          case 882: {
            BizExt = input.ReadBytes();
            break;
          }
          case 890: {
            SceneExt = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Uid = input.ReadInt64();
            break;
          }
          case 18: {
            ShowUid = input.ReadString();
            break;
          }
          case 26: {
            Nickname = input.ReadString();
            break;
          }
          case 34: {
            Avatar = input.ReadString();
            break;
          }
          case 40: {
            RegisteredAt = input.ReadInt64();
            break;
          }
          case 48: {
            Gender = (global::Scommon.Gender) input.ReadEnum();
            break;
          }
          case 58: {
            if (countryInfo_ == null) {
              CountryInfo = new global::Pbaccount.CountryInfo();
            }
            input.ReadMessage(CountryInfo);
            break;
          }
          case 160: {
            Status = (global::Comm.Api.Adapter.UserStatus) input.ReadEnum();
            break;
          }
          case 242: {
            Birthday = input.ReadString();
            break;
          }
          case 248: {
            Age = input.ReadInt32();
            break;
          }
          case 322: {
            Introduction = input.ReadString();
            break;
          }
          case 402: {
            City = input.ReadString();
            break;
          }
          case 802: {
            Language = input.ReadString();
            break;
          }
          case 882: {
            BizExt = input.ReadBytes();
            break;
          }
          case 890: {
            SceneExt = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
