// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protobuf/svr/privilege/pretty_number.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Svr.Privilege {

  /// <summary>Holder for reflection information generated from protobuf/svr/privilege/pretty_number.proto</summary>
  public static partial class PrettyNumberReflection {

    #region Descriptor
    /// <summary>File descriptor for protobuf/svr/privilege/pretty_number.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PrettyNumberReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cipwcm90b2J1Zi9zdnIvcHJpdmlsZWdlL3ByZXR0eV9udW1iZXIucHJvdG8S",
            "DXN2ci5wcml2aWxlZ2UaKXByb3RvYnVmL2FwaS9wcml2aWxlZ2UvdjIvcHJp",
            "dmlsZWdlLnByb3RvIqQDCgxQcmV0dHlOdW1iZXISCgoCaWQYASABKAMSEQoJ",
            "b3duZXJfdWlkGAIgASgDEg8KB3Nob3dfaWQYAyABKAkSMQoLdGFyZ2V0X3R5",
            "cGUYBCABKA4yHC5hcGkucHJpdmlsZWdlLnYyLlRhcmdldFR5cGUSEQoJdGFy",
            "Z2V0X2lkGAUgASgDEi4KBmFzc2V0cxgGIAEoCzIeLmFwaS5wcml2aWxlZ2Uu",
            "djIuUHJldHR5TnVtYmVyEhIKCmV4cGlyZWRfYXQYByABKAMSOwoKdXNlX3N0",
            "YXR1cxgIIAEoDjInLmFwaS5wcml2aWxlZ2UudjIuUHJldHR5TnVtYmVyVXNl",
            "U3RhdHVzEj0KC2JpbmRfc3RhdHVzGAkgASgOMiguYXBpLnByaXZpbGVnZS52",
            "Mi5QcmV0dHlOdW1iZXJCaW5kU3RhdHVzEg4KBnJlbWFyaxgKIAEoCRINCgVj",
            "dGltZRgLIAEoAxINCgV1dGltZRgMIAEoAxIPCgdjcmVhdG9yGA0gASgJEg4K",
            "BmVkaXRvchgOIAEoCRIPCgdleHBpcmVkGA8gASgFInIKF0JhdGNoR2V0UHJl",
            "dHR5TnVtYmVyUmVxEjEKC3RhcmdldF90eXBlGAEgASgOMhwuYXBpLnByaXZp",
            "bGVnZS52Mi5UYXJnZXRUeXBlEhIKCnRhcmdldF9pZHMYAiADKAMSEAoIc2hv",
            "d19pZHMYAyADKAkiTgoXQmF0Y2hHZXRQcmV0dHlOdW1iZXJSc3ASMwoOcHJl",
            "dHR5X251bWJlcnMYASADKAsyGy5zdnIucHJpdmlsZWdlLlByZXR0eU51bWJl",
            "ciIqChtCYXRjaEdldFByZXR0eU51bWJlckJ5SURSZXESCwoDaWRzGAEgAygD",
            "IscBChtCYXRjaEdldFByZXR0eU51bWJlckJ5SURSc3ASVQoOcHJldHR5X251",
            "bWJlcnMYASADKAsyPS5zdnIucHJpdmlsZWdlLkJhdGNoR2V0UHJldHR5TnVt",
            "YmVyQnlJRFJzcC5QcmV0dHlOdW1iZXJzRW50cnkaUQoSUHJldHR5TnVtYmVy",
            "c0VudHJ5EgsKA2tleRgBIAEoAxIqCgV2YWx1ZRgCIAEoCzIbLnN2ci5wcml2",
            "aWxlZ2UuUHJldHR5TnVtYmVyOgI4ASKtAQoTQmluZFByZXR0eU51bWJlclJl",
            "cRIOCgZzZXFfaWQYASABKAkSGAoQcHJldHR5X251bWJlcl9pZBgCIAEoAxIR",
            "Cglvd25lcl91aWQYCiABKAMSMQoLdGFyZ2V0X3R5cGUYFCABKA4yHC5hcGku",
            "cHJpdmlsZWdlLnYyLlRhcmdldFR5cGUSEQoJdGFyZ2V0X2lkGBUgASgDEhMK",
            "C2V4cGlyZV9zZWNzGB4gASgDIhUKE0JpbmRQcmV0dHlOdW1iZXJSc3AyyQIK",
            "D1ByZXR0eU51bWJlclN2chJmChRCYXRjaEdldFByZXR0eU51bWJlchImLnN2",
            "ci5wcml2aWxlZ2UuQmF0Y2hHZXRQcmV0dHlOdW1iZXJSZXEaJi5zdnIucHJp",
            "dmlsZWdlLkJhdGNoR2V0UHJldHR5TnVtYmVyUnNwEnIKGEJhdGNoR2V0UHJl",
            "dHR5TnVtYmVyQnlJRBIqLnN2ci5wcml2aWxlZ2UuQmF0Y2hHZXRQcmV0dHlO",
            "dW1iZXJCeUlEUmVxGiouc3ZyLnByaXZpbGVnZS5CYXRjaEdldFByZXR0eU51",
            "bWJlckJ5SURSc3ASWgoQQmluZFByZXR0eU51bWJlchIiLnN2ci5wcml2aWxl",
            "Z2UuQmluZFByZXR0eU51bWJlclJlcRoiLnN2ci5wcml2aWxlZ2UuQmluZFBy",
            "ZXR0eU51bWJlclJzcEIzWjFnaXRpdC5jYy9zb2NpYWwvcHJvdG9idWYvZ2Vu",
            "Y29kZS9zdnIvcGJzcHJpdmlsZWdlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Api.Privilege.V2.PrivilegeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Svr.Privilege.PrettyNumber), global::Svr.Privilege.PrettyNumber.Parser, new[]{ "Id", "OwnerUid", "ShowId", "TargetType", "TargetId", "Assets", "ExpiredAt", "UseStatus", "BindStatus", "Remark", "Ctime", "Utime", "Creator", "Editor", "Expired" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Svr.Privilege.BatchGetPrettyNumberReq), global::Svr.Privilege.BatchGetPrettyNumberReq.Parser, new[]{ "TargetType", "TargetIds", "ShowIds" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Svr.Privilege.BatchGetPrettyNumberRsp), global::Svr.Privilege.BatchGetPrettyNumberRsp.Parser, new[]{ "PrettyNumbers" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Svr.Privilege.BatchGetPrettyNumberByIDReq), global::Svr.Privilege.BatchGetPrettyNumberByIDReq.Parser, new[]{ "Ids" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Svr.Privilege.BatchGetPrettyNumberByIDRsp), global::Svr.Privilege.BatchGetPrettyNumberByIDRsp.Parser, new[]{ "PrettyNumbers" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Svr.Privilege.BindPrettyNumberReq), global::Svr.Privilege.BindPrettyNumberReq.Parser, new[]{ "SeqId", "PrettyNumberId", "OwnerUid", "TargetType", "TargetId", "ExpireSecs" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Svr.Privilege.BindPrettyNumberRsp), global::Svr.Privilege.BindPrettyNumberRsp.Parser, null, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PrettyNumber : pb::IMessage<PrettyNumber>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PrettyNumber> _parser = new pb::MessageParser<PrettyNumber>(() => new PrettyNumber());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PrettyNumber> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Svr.Privilege.PrettyNumberReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PrettyNumber() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PrettyNumber(PrettyNumber other) : this() {
      id_ = other.id_;
      ownerUid_ = other.ownerUid_;
      showId_ = other.showId_;
      targetType_ = other.targetType_;
      targetId_ = other.targetId_;
      assets_ = other.assets_ != null ? other.assets_.Clone() : null;
      expiredAt_ = other.expiredAt_;
      useStatus_ = other.useStatus_;
      bindStatus_ = other.bindStatus_;
      remark_ = other.remark_;
      ctime_ = other.ctime_;
      utime_ = other.utime_;
      creator_ = other.creator_;
      editor_ = other.editor_;
      expired_ = other.expired_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PrettyNumber Clone() {
      return new PrettyNumber(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "owner_uid" field.</summary>
    public const int OwnerUidFieldNumber = 2;
    private long ownerUid_;
    /// <summary>
    /// 靓号拥有者uid
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long OwnerUid {
      get { return ownerUid_; }
      set {
        ownerUid_ = value;
      }
    }

    /// <summary>Field number for the "show_id" field.</summary>
    public const int ShowIdFieldNumber = 3;
    private string showId_ = "";
    /// <summary>
    /// 靓号号码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ShowId {
      get { return showId_; }
      set {
        showId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "target_type" field.</summary>
    public const int TargetTypeFieldNumber = 4;
    private global::Api.Privilege.V2.TargetType targetType_ = global::Api.Privilege.V2.TargetType.None;
    /// <summary>
    /// 归属类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Privilege.V2.TargetType TargetType {
      get { return targetType_; }
      set {
        targetType_ = value;
      }
    }

    /// <summary>Field number for the "target_id" field.</summary>
    public const int TargetIdFieldNumber = 5;
    private long targetId_;
    /// <summary>
    ///归属目标id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TargetId {
      get { return targetId_; }
      set {
        targetId_ = value;
      }
    }

    /// <summary>Field number for the "assets" field.</summary>
    public const int AssetsFieldNumber = 6;
    private global::Api.Privilege.V2.PrettyNumber assets_;
    /// <summary>
    ///资源
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Privilege.V2.PrettyNumber Assets {
      get { return assets_; }
      set {
        assets_ = value;
      }
    }

    /// <summary>Field number for the "expired_at" field.</summary>
    public const int ExpiredAtFieldNumber = 7;
    private long expiredAt_;
    /// <summary>
    /// 过期时间戳-秒(-1:永久)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ExpiredAt {
      get { return expiredAt_; }
      set {
        expiredAt_ = value;
      }
    }

    /// <summary>Field number for the "use_status" field.</summary>
    public const int UseStatusFieldNumber = 8;
    private global::Api.Privilege.V2.PrettyNumberUseStatus useStatus_ = global::Api.Privilege.V2.PrettyNumberUseStatus.None;
    /// <summary>
    /// 使用状态
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Privilege.V2.PrettyNumberUseStatus UseStatus {
      get { return useStatus_; }
      set {
        useStatus_ = value;
      }
    }

    /// <summary>Field number for the "bind_status" field.</summary>
    public const int BindStatusFieldNumber = 9;
    private global::Api.Privilege.V2.PrettyNumberBindStatus bindStatus_ = global::Api.Privilege.V2.PrettyNumberBindStatus.None;
    /// <summary>
    /// 绑定状态
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Privilege.V2.PrettyNumberBindStatus BindStatus {
      get { return bindStatus_; }
      set {
        bindStatus_ = value;
      }
    }

    /// <summary>Field number for the "remark" field.</summary>
    public const int RemarkFieldNumber = 10;
    private string remark_ = "";
    /// <summary>
    ///备注
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Remark {
      get { return remark_; }
      set {
        remark_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ctime" field.</summary>
    public const int CtimeFieldNumber = 11;
    private long ctime_;
    /// <summary>
    ///创建时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Ctime {
      get { return ctime_; }
      set {
        ctime_ = value;
      }
    }

    /// <summary>Field number for the "utime" field.</summary>
    public const int UtimeFieldNumber = 12;
    private long utime_;
    /// <summary>
    ///更新时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Utime {
      get { return utime_; }
      set {
        utime_ = value;
      }
    }

    /// <summary>Field number for the "creator" field.</summary>
    public const int CreatorFieldNumber = 13;
    private string creator_ = "";
    /// <summary>
    ///创建人
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Creator {
      get { return creator_; }
      set {
        creator_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "editor" field.</summary>
    public const int EditorFieldNumber = 14;
    private string editor_ = "";
    /// <summary>
    ///编辑
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Editor {
      get { return editor_; }
      set {
        editor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "expired" field.</summary>
    public const int ExpiredFieldNumber = 15;
    private int expired_;
    /// <summary>
    ///是否标记为已过期, 定时任务使用, 1-未过期, 2-已过期
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Expired {
      get { return expired_; }
      set {
        expired_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PrettyNumber);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PrettyNumber other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (OwnerUid != other.OwnerUid) return false;
      if (ShowId != other.ShowId) return false;
      if (TargetType != other.TargetType) return false;
      if (TargetId != other.TargetId) return false;
      if (!object.Equals(Assets, other.Assets)) return false;
      if (ExpiredAt != other.ExpiredAt) return false;
      if (UseStatus != other.UseStatus) return false;
      if (BindStatus != other.BindStatus) return false;
      if (Remark != other.Remark) return false;
      if (Ctime != other.Ctime) return false;
      if (Utime != other.Utime) return false;
      if (Creator != other.Creator) return false;
      if (Editor != other.Editor) return false;
      if (Expired != other.Expired) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (OwnerUid != 0L) hash ^= OwnerUid.GetHashCode();
      if (ShowId.Length != 0) hash ^= ShowId.GetHashCode();
      if (TargetType != global::Api.Privilege.V2.TargetType.None) hash ^= TargetType.GetHashCode();
      if (TargetId != 0L) hash ^= TargetId.GetHashCode();
      if (assets_ != null) hash ^= Assets.GetHashCode();
      if (ExpiredAt != 0L) hash ^= ExpiredAt.GetHashCode();
      if (UseStatus != global::Api.Privilege.V2.PrettyNumberUseStatus.None) hash ^= UseStatus.GetHashCode();
      if (BindStatus != global::Api.Privilege.V2.PrettyNumberBindStatus.None) hash ^= BindStatus.GetHashCode();
      if (Remark.Length != 0) hash ^= Remark.GetHashCode();
      if (Ctime != 0L) hash ^= Ctime.GetHashCode();
      if (Utime != 0L) hash ^= Utime.GetHashCode();
      if (Creator.Length != 0) hash ^= Creator.GetHashCode();
      if (Editor.Length != 0) hash ^= Editor.GetHashCode();
      if (Expired != 0) hash ^= Expired.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (OwnerUid != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(OwnerUid);
      }
      if (ShowId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ShowId);
      }
      if (TargetType != global::Api.Privilege.V2.TargetType.None) {
        output.WriteRawTag(32);
        output.WriteEnum((int) TargetType);
      }
      if (TargetId != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(TargetId);
      }
      if (assets_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Assets);
      }
      if (ExpiredAt != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(ExpiredAt);
      }
      if (UseStatus != global::Api.Privilege.V2.PrettyNumberUseStatus.None) {
        output.WriteRawTag(64);
        output.WriteEnum((int) UseStatus);
      }
      if (BindStatus != global::Api.Privilege.V2.PrettyNumberBindStatus.None) {
        output.WriteRawTag(72);
        output.WriteEnum((int) BindStatus);
      }
      if (Remark.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Remark);
      }
      if (Ctime != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(Ctime);
      }
      if (Utime != 0L) {
        output.WriteRawTag(96);
        output.WriteInt64(Utime);
      }
      if (Creator.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(Creator);
      }
      if (Editor.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(Editor);
      }
      if (Expired != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(Expired);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (OwnerUid != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(OwnerUid);
      }
      if (ShowId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ShowId);
      }
      if (TargetType != global::Api.Privilege.V2.TargetType.None) {
        output.WriteRawTag(32);
        output.WriteEnum((int) TargetType);
      }
      if (TargetId != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(TargetId);
      }
      if (assets_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Assets);
      }
      if (ExpiredAt != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(ExpiredAt);
      }
      if (UseStatus != global::Api.Privilege.V2.PrettyNumberUseStatus.None) {
        output.WriteRawTag(64);
        output.WriteEnum((int) UseStatus);
      }
      if (BindStatus != global::Api.Privilege.V2.PrettyNumberBindStatus.None) {
        output.WriteRawTag(72);
        output.WriteEnum((int) BindStatus);
      }
      if (Remark.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Remark);
      }
      if (Ctime != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(Ctime);
      }
      if (Utime != 0L) {
        output.WriteRawTag(96);
        output.WriteInt64(Utime);
      }
      if (Creator.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(Creator);
      }
      if (Editor.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(Editor);
      }
      if (Expired != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(Expired);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (OwnerUid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(OwnerUid);
      }
      if (ShowId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ShowId);
      }
      if (TargetType != global::Api.Privilege.V2.TargetType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TargetType);
      }
      if (TargetId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TargetId);
      }
      if (assets_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Assets);
      }
      if (ExpiredAt != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ExpiredAt);
      }
      if (UseStatus != global::Api.Privilege.V2.PrettyNumberUseStatus.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UseStatus);
      }
      if (BindStatus != global::Api.Privilege.V2.PrettyNumberBindStatus.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) BindStatus);
      }
      if (Remark.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Remark);
      }
      if (Ctime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Ctime);
      }
      if (Utime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Utime);
      }
      if (Creator.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Creator);
      }
      if (Editor.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Editor);
      }
      if (Expired != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Expired);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PrettyNumber other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.OwnerUid != 0L) {
        OwnerUid = other.OwnerUid;
      }
      if (other.ShowId.Length != 0) {
        ShowId = other.ShowId;
      }
      if (other.TargetType != global::Api.Privilege.V2.TargetType.None) {
        TargetType = other.TargetType;
      }
      if (other.TargetId != 0L) {
        TargetId = other.TargetId;
      }
      if (other.assets_ != null) {
        if (assets_ == null) {
          Assets = new global::Api.Privilege.V2.PrettyNumber();
        }
        Assets.MergeFrom(other.Assets);
      }
      if (other.ExpiredAt != 0L) {
        ExpiredAt = other.ExpiredAt;
      }
      if (other.UseStatus != global::Api.Privilege.V2.PrettyNumberUseStatus.None) {
        UseStatus = other.UseStatus;
      }
      if (other.BindStatus != global::Api.Privilege.V2.PrettyNumberBindStatus.None) {
        BindStatus = other.BindStatus;
      }
      if (other.Remark.Length != 0) {
        Remark = other.Remark;
      }
      if (other.Ctime != 0L) {
        Ctime = other.Ctime;
      }
      if (other.Utime != 0L) {
        Utime = other.Utime;
      }
      if (other.Creator.Length != 0) {
        Creator = other.Creator;
      }
      if (other.Editor.Length != 0) {
        Editor = other.Editor;
      }
      if (other.Expired != 0) {
        Expired = other.Expired;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            OwnerUid = input.ReadInt64();
            break;
          }
          case 26: {
            ShowId = input.ReadString();
            break;
          }
          case 32: {
            TargetType = (global::Api.Privilege.V2.TargetType) input.ReadEnum();
            break;
          }
          case 40: {
            TargetId = input.ReadInt64();
            break;
          }
          case 50: {
            if (assets_ == null) {
              Assets = new global::Api.Privilege.V2.PrettyNumber();
            }
            input.ReadMessage(Assets);
            break;
          }
          case 56: {
            ExpiredAt = input.ReadInt64();
            break;
          }
          case 64: {
            UseStatus = (global::Api.Privilege.V2.PrettyNumberUseStatus) input.ReadEnum();
            break;
          }
          case 72: {
            BindStatus = (global::Api.Privilege.V2.PrettyNumberBindStatus) input.ReadEnum();
            break;
          }
          case 82: {
            Remark = input.ReadString();
            break;
          }
          case 88: {
            Ctime = input.ReadInt64();
            break;
          }
          case 96: {
            Utime = input.ReadInt64();
            break;
          }
          case 106: {
            Creator = input.ReadString();
            break;
          }
          case 114: {
            Editor = input.ReadString();
            break;
          }
          case 120: {
            Expired = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            OwnerUid = input.ReadInt64();
            break;
          }
          case 26: {
            ShowId = input.ReadString();
            break;
          }
          case 32: {
            TargetType = (global::Api.Privilege.V2.TargetType) input.ReadEnum();
            break;
          }
          case 40: {
            TargetId = input.ReadInt64();
            break;
          }
          case 50: {
            if (assets_ == null) {
              Assets = new global::Api.Privilege.V2.PrettyNumber();
            }
            input.ReadMessage(Assets);
            break;
          }
          case 56: {
            ExpiredAt = input.ReadInt64();
            break;
          }
          case 64: {
            UseStatus = (global::Api.Privilege.V2.PrettyNumberUseStatus) input.ReadEnum();
            break;
          }
          case 72: {
            BindStatus = (global::Api.Privilege.V2.PrettyNumberBindStatus) input.ReadEnum();
            break;
          }
          case 82: {
            Remark = input.ReadString();
            break;
          }
          case 88: {
            Ctime = input.ReadInt64();
            break;
          }
          case 96: {
            Utime = input.ReadInt64();
            break;
          }
          case 106: {
            Creator = input.ReadString();
            break;
          }
          case 114: {
            Editor = input.ReadString();
            break;
          }
          case 120: {
            Expired = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BatchGetPrettyNumberReq : pb::IMessage<BatchGetPrettyNumberReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BatchGetPrettyNumberReq> _parser = new pb::MessageParser<BatchGetPrettyNumberReq>(() => new BatchGetPrettyNumberReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BatchGetPrettyNumberReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Svr.Privilege.PrettyNumberReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BatchGetPrettyNumberReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BatchGetPrettyNumberReq(BatchGetPrettyNumberReq other) : this() {
      targetType_ = other.targetType_;
      targetIds_ = other.targetIds_.Clone();
      showIds_ = other.showIds_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BatchGetPrettyNumberReq Clone() {
      return new BatchGetPrettyNumberReq(this);
    }

    /// <summary>Field number for the "target_type" field.</summary>
    public const int TargetTypeFieldNumber = 1;
    private global::Api.Privilege.V2.TargetType targetType_ = global::Api.Privilege.V2.TargetType.None;
    /// <summary>
    /// 归属类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Privilege.V2.TargetType TargetType {
      get { return targetType_; }
      set {
        targetType_ = value;
      }
    }

    /// <summary>Field number for the "target_ids" field.</summary>
    public const int TargetIdsFieldNumber = 2;
    private static readonly pb::FieldCodec<long> _repeated_targetIds_codec
        = pb::FieldCodec.ForInt64(18);
    private readonly pbc::RepeatedField<long> targetIds_ = new pbc::RepeatedField<long>();
    /// <summary>
    /// uid / room_id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<long> TargetIds {
      get { return targetIds_; }
    }

    /// <summary>Field number for the "show_ids" field.</summary>
    public const int ShowIdsFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_showIds_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> showIds_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// 靓号ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> ShowIds {
      get { return showIds_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BatchGetPrettyNumberReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BatchGetPrettyNumberReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TargetType != other.TargetType) return false;
      if(!targetIds_.Equals(other.targetIds_)) return false;
      if(!showIds_.Equals(other.showIds_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TargetType != global::Api.Privilege.V2.TargetType.None) hash ^= TargetType.GetHashCode();
      hash ^= targetIds_.GetHashCode();
      hash ^= showIds_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TargetType != global::Api.Privilege.V2.TargetType.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) TargetType);
      }
      targetIds_.WriteTo(output, _repeated_targetIds_codec);
      showIds_.WriteTo(output, _repeated_showIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TargetType != global::Api.Privilege.V2.TargetType.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) TargetType);
      }
      targetIds_.WriteTo(ref output, _repeated_targetIds_codec);
      showIds_.WriteTo(ref output, _repeated_showIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TargetType != global::Api.Privilege.V2.TargetType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TargetType);
      }
      size += targetIds_.CalculateSize(_repeated_targetIds_codec);
      size += showIds_.CalculateSize(_repeated_showIds_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BatchGetPrettyNumberReq other) {
      if (other == null) {
        return;
      }
      if (other.TargetType != global::Api.Privilege.V2.TargetType.None) {
        TargetType = other.TargetType;
      }
      targetIds_.Add(other.targetIds_);
      showIds_.Add(other.showIds_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TargetType = (global::Api.Privilege.V2.TargetType) input.ReadEnum();
            break;
          }
          case 18:
          case 16: {
            targetIds_.AddEntriesFrom(input, _repeated_targetIds_codec);
            break;
          }
          case 26: {
            showIds_.AddEntriesFrom(input, _repeated_showIds_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TargetType = (global::Api.Privilege.V2.TargetType) input.ReadEnum();
            break;
          }
          case 18:
          case 16: {
            targetIds_.AddEntriesFrom(ref input, _repeated_targetIds_codec);
            break;
          }
          case 26: {
            showIds_.AddEntriesFrom(ref input, _repeated_showIds_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BatchGetPrettyNumberRsp : pb::IMessage<BatchGetPrettyNumberRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BatchGetPrettyNumberRsp> _parser = new pb::MessageParser<BatchGetPrettyNumberRsp>(() => new BatchGetPrettyNumberRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BatchGetPrettyNumberRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Svr.Privilege.PrettyNumberReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BatchGetPrettyNumberRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BatchGetPrettyNumberRsp(BatchGetPrettyNumberRsp other) : this() {
      prettyNumbers_ = other.prettyNumbers_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BatchGetPrettyNumberRsp Clone() {
      return new BatchGetPrettyNumberRsp(this);
    }

    /// <summary>Field number for the "pretty_numbers" field.</summary>
    public const int PrettyNumbersFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Svr.Privilege.PrettyNumber> _repeated_prettyNumbers_codec
        = pb::FieldCodec.ForMessage(10, global::Svr.Privilege.PrettyNumber.Parser);
    private readonly pbc::RepeatedField<global::Svr.Privilege.PrettyNumber> prettyNumbers_ = new pbc::RepeatedField<global::Svr.Privilege.PrettyNumber>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Svr.Privilege.PrettyNumber> PrettyNumbers {
      get { return prettyNumbers_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BatchGetPrettyNumberRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BatchGetPrettyNumberRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!prettyNumbers_.Equals(other.prettyNumbers_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= prettyNumbers_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      prettyNumbers_.WriteTo(output, _repeated_prettyNumbers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      prettyNumbers_.WriteTo(ref output, _repeated_prettyNumbers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += prettyNumbers_.CalculateSize(_repeated_prettyNumbers_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BatchGetPrettyNumberRsp other) {
      if (other == null) {
        return;
      }
      prettyNumbers_.Add(other.prettyNumbers_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            prettyNumbers_.AddEntriesFrom(input, _repeated_prettyNumbers_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            prettyNumbers_.AddEntriesFrom(ref input, _repeated_prettyNumbers_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BatchGetPrettyNumberByIDReq : pb::IMessage<BatchGetPrettyNumberByIDReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BatchGetPrettyNumberByIDReq> _parser = new pb::MessageParser<BatchGetPrettyNumberByIDReq>(() => new BatchGetPrettyNumberByIDReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BatchGetPrettyNumberByIDReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Svr.Privilege.PrettyNumberReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BatchGetPrettyNumberByIDReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BatchGetPrettyNumberByIDReq(BatchGetPrettyNumberByIDReq other) : this() {
      ids_ = other.ids_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BatchGetPrettyNumberByIDReq Clone() {
      return new BatchGetPrettyNumberByIDReq(this);
    }

    /// <summary>Field number for the "ids" field.</summary>
    public const int IdsFieldNumber = 1;
    private static readonly pb::FieldCodec<long> _repeated_ids_codec
        = pb::FieldCodec.ForInt64(10);
    private readonly pbc::RepeatedField<long> ids_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<long> Ids {
      get { return ids_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BatchGetPrettyNumberByIDReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BatchGetPrettyNumberByIDReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!ids_.Equals(other.ids_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= ids_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      ids_.WriteTo(output, _repeated_ids_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      ids_.WriteTo(ref output, _repeated_ids_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += ids_.CalculateSize(_repeated_ids_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BatchGetPrettyNumberByIDReq other) {
      if (other == null) {
        return;
      }
      ids_.Add(other.ids_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            ids_.AddEntriesFrom(input, _repeated_ids_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 8: {
            ids_.AddEntriesFrom(ref input, _repeated_ids_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BatchGetPrettyNumberByIDRsp : pb::IMessage<BatchGetPrettyNumberByIDRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BatchGetPrettyNumberByIDRsp> _parser = new pb::MessageParser<BatchGetPrettyNumberByIDRsp>(() => new BatchGetPrettyNumberByIDRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BatchGetPrettyNumberByIDRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Svr.Privilege.PrettyNumberReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BatchGetPrettyNumberByIDRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BatchGetPrettyNumberByIDRsp(BatchGetPrettyNumberByIDRsp other) : this() {
      prettyNumbers_ = other.prettyNumbers_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BatchGetPrettyNumberByIDRsp Clone() {
      return new BatchGetPrettyNumberByIDRsp(this);
    }

    /// <summary>Field number for the "pretty_numbers" field.</summary>
    public const int PrettyNumbersFieldNumber = 1;
    private static readonly pbc::MapField<long, global::Svr.Privilege.PrettyNumber>.Codec _map_prettyNumbers_codec
        = new pbc::MapField<long, global::Svr.Privilege.PrettyNumber>.Codec(pb::FieldCodec.ForInt64(8, 0L), pb::FieldCodec.ForMessage(18, global::Svr.Privilege.PrettyNumber.Parser), 10);
    private readonly pbc::MapField<long, global::Svr.Privilege.PrettyNumber> prettyNumbers_ = new pbc::MapField<long, global::Svr.Privilege.PrettyNumber>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<long, global::Svr.Privilege.PrettyNumber> PrettyNumbers {
      get { return prettyNumbers_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BatchGetPrettyNumberByIDRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BatchGetPrettyNumberByIDRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!PrettyNumbers.Equals(other.PrettyNumbers)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= PrettyNumbers.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      prettyNumbers_.WriteTo(output, _map_prettyNumbers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      prettyNumbers_.WriteTo(ref output, _map_prettyNumbers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += prettyNumbers_.CalculateSize(_map_prettyNumbers_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BatchGetPrettyNumberByIDRsp other) {
      if (other == null) {
        return;
      }
      prettyNumbers_.MergeFrom(other.prettyNumbers_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            prettyNumbers_.AddEntriesFrom(input, _map_prettyNumbers_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            prettyNumbers_.AddEntriesFrom(ref input, _map_prettyNumbers_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BindPrettyNumberReq : pb::IMessage<BindPrettyNumberReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BindPrettyNumberReq> _parser = new pb::MessageParser<BindPrettyNumberReq>(() => new BindPrettyNumberReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BindPrettyNumberReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Svr.Privilege.PrettyNumberReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BindPrettyNumberReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BindPrettyNumberReq(BindPrettyNumberReq other) : this() {
      seqId_ = other.seqId_;
      prettyNumberId_ = other.prettyNumberId_;
      ownerUid_ = other.ownerUid_;
      targetType_ = other.targetType_;
      targetId_ = other.targetId_;
      expireSecs_ = other.expireSecs_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BindPrettyNumberReq Clone() {
      return new BindPrettyNumberReq(this);
    }

    /// <summary>Field number for the "seq_id" field.</summary>
    public const int SeqIdFieldNumber = 1;
    private string seqId_ = "";
    /// <summary>
    /// 幂等ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SeqId {
      get { return seqId_; }
      set {
        seqId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pretty_number_id" field.</summary>
    public const int PrettyNumberIdFieldNumber = 2;
    private long prettyNumberId_;
    /// <summary>
    /// 靓号ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PrettyNumberId {
      get { return prettyNumberId_; }
      set {
        prettyNumberId_ = value;
      }
    }

    /// <summary>Field number for the "owner_uid" field.</summary>
    public const int OwnerUidFieldNumber = 10;
    private long ownerUid_;
    /// <summary>
    /// 归属人
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long OwnerUid {
      get { return ownerUid_; }
      set {
        ownerUid_ = value;
      }
    }

    /// <summary>Field number for the "target_type" field.</summary>
    public const int TargetTypeFieldNumber = 20;
    private global::Api.Privilege.V2.TargetType targetType_ = global::Api.Privilege.V2.TargetType.None;
    /// <summary>
    /// 归属类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Privilege.V2.TargetType TargetType {
      get { return targetType_; }
      set {
        targetType_ = value;
      }
    }

    /// <summary>Field number for the "target_id" field.</summary>
    public const int TargetIdFieldNumber = 21;
    private long targetId_;
    /// <summary>
    /// 归属目标id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TargetId {
      get { return targetId_; }
      set {
        targetId_ = value;
      }
    }

    /// <summary>Field number for the "expire_secs" field.</summary>
    public const int ExpireSecsFieldNumber = 30;
    private long expireSecs_;
    /// <summary>
    /// 过期时间戳-秒(-1:永久)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ExpireSecs {
      get { return expireSecs_; }
      set {
        expireSecs_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BindPrettyNumberReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BindPrettyNumberReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SeqId != other.SeqId) return false;
      if (PrettyNumberId != other.PrettyNumberId) return false;
      if (OwnerUid != other.OwnerUid) return false;
      if (TargetType != other.TargetType) return false;
      if (TargetId != other.TargetId) return false;
      if (ExpireSecs != other.ExpireSecs) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SeqId.Length != 0) hash ^= SeqId.GetHashCode();
      if (PrettyNumberId != 0L) hash ^= PrettyNumberId.GetHashCode();
      if (OwnerUid != 0L) hash ^= OwnerUid.GetHashCode();
      if (TargetType != global::Api.Privilege.V2.TargetType.None) hash ^= TargetType.GetHashCode();
      if (TargetId != 0L) hash ^= TargetId.GetHashCode();
      if (ExpireSecs != 0L) hash ^= ExpireSecs.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SeqId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SeqId);
      }
      if (PrettyNumberId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(PrettyNumberId);
      }
      if (OwnerUid != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(OwnerUid);
      }
      if (TargetType != global::Api.Privilege.V2.TargetType.None) {
        output.WriteRawTag(160, 1);
        output.WriteEnum((int) TargetType);
      }
      if (TargetId != 0L) {
        output.WriteRawTag(168, 1);
        output.WriteInt64(TargetId);
      }
      if (ExpireSecs != 0L) {
        output.WriteRawTag(240, 1);
        output.WriteInt64(ExpireSecs);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SeqId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SeqId);
      }
      if (PrettyNumberId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(PrettyNumberId);
      }
      if (OwnerUid != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(OwnerUid);
      }
      if (TargetType != global::Api.Privilege.V2.TargetType.None) {
        output.WriteRawTag(160, 1);
        output.WriteEnum((int) TargetType);
      }
      if (TargetId != 0L) {
        output.WriteRawTag(168, 1);
        output.WriteInt64(TargetId);
      }
      if (ExpireSecs != 0L) {
        output.WriteRawTag(240, 1);
        output.WriteInt64(ExpireSecs);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SeqId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SeqId);
      }
      if (PrettyNumberId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PrettyNumberId);
      }
      if (OwnerUid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(OwnerUid);
      }
      if (TargetType != global::Api.Privilege.V2.TargetType.None) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) TargetType);
      }
      if (TargetId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(TargetId);
      }
      if (ExpireSecs != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ExpireSecs);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BindPrettyNumberReq other) {
      if (other == null) {
        return;
      }
      if (other.SeqId.Length != 0) {
        SeqId = other.SeqId;
      }
      if (other.PrettyNumberId != 0L) {
        PrettyNumberId = other.PrettyNumberId;
      }
      if (other.OwnerUid != 0L) {
        OwnerUid = other.OwnerUid;
      }
      if (other.TargetType != global::Api.Privilege.V2.TargetType.None) {
        TargetType = other.TargetType;
      }
      if (other.TargetId != 0L) {
        TargetId = other.TargetId;
      }
      if (other.ExpireSecs != 0L) {
        ExpireSecs = other.ExpireSecs;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SeqId = input.ReadString();
            break;
          }
          case 16: {
            PrettyNumberId = input.ReadInt64();
            break;
          }
          case 80: {
            OwnerUid = input.ReadInt64();
            break;
          }
          case 160: {
            TargetType = (global::Api.Privilege.V2.TargetType) input.ReadEnum();
            break;
          }
          case 168: {
            TargetId = input.ReadInt64();
            break;
          }
          case 240: {
            ExpireSecs = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SeqId = input.ReadString();
            break;
          }
          case 16: {
            PrettyNumberId = input.ReadInt64();
            break;
          }
          case 80: {
            OwnerUid = input.ReadInt64();
            break;
          }
          case 160: {
            TargetType = (global::Api.Privilege.V2.TargetType) input.ReadEnum();
            break;
          }
          case 168: {
            TargetId = input.ReadInt64();
            break;
          }
          case 240: {
            ExpireSecs = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BindPrettyNumberRsp : pb::IMessage<BindPrettyNumberRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BindPrettyNumberRsp> _parser = new pb::MessageParser<BindPrettyNumberRsp>(() => new BindPrettyNumberRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BindPrettyNumberRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Svr.Privilege.PrettyNumberReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BindPrettyNumberRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BindPrettyNumberRsp(BindPrettyNumberRsp other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BindPrettyNumberRsp Clone() {
      return new BindPrettyNumberRsp(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BindPrettyNumberRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BindPrettyNumberRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BindPrettyNumberRsp other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
