// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protobuf/svr/privilege/resource_bag_mq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Svr.Privilege {

  /// <summary>Holder for reflection information generated from protobuf/svr/privilege/resource_bag_mq.proto</summary>
  public static partial class ResourceBagMqReflection {

    #region Descriptor
    /// <summary>File descriptor for protobuf/svr/privilege/resource_bag_mq.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResourceBagMqReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cixwcm90b2J1Zi9zdnIvcHJpdmlsZWdlL3Jlc291cmNlX2JhZ19tcS5wcm90",
            "bxINc3ZyLnByaXZpbGVnZRoscHJvdG9idWYvYXBpL3ByaXZpbGVnZS92Mi9y",
            "ZXNvdXJjZV9iYWcucHJvdG8aMHByb3RvYnVmL2FwaS9wcml2aWxlZ2UvdjIv",
            "cmVzb3VyY2VfcGFja2FnZS5wcm90bxopcHJvdG9idWYvYXBpL3ByaXZpbGVn",
            "ZS92Mi9wcml2aWxlZ2UucHJvdG8itQEKEFJlc291cmNlQmFnRXZlbnQSCwoD",
            "YW5tGAEgASgJEg8KB3N1Yl9hbm0YAiABKAkSEgoKZXZlbnRfdGltZRgDIAEo",
            "AxI3CgpldmVudF90eXBlGAQgASgOMiMuc3ZyLnByaXZpbGVnZS5SZXNvdXJj",
            "ZUJhZ0V2ZW50VHlwZRI2CgdkZXRhaWxzGAUgAygLMiUuc3ZyLnByaXZpbGVn",
            "ZS5SZXNvdXJjZUJhZ0V2ZW50RGV0YWlsIqIBChZSZXNvdXJjZUJhZ0V2ZW50",
            "RGV0YWlsEjwKCGFsbG9jYXRlGAEgASgLMiguc3ZyLnByaXZpbGVnZS5SZXNv",
            "dXJjZUJhZ0FsbG9jYXRlRGV0YWlsSAASQAoKZGlzdHJpYnV0ZRgCIAEoCzIq",
            "LnN2ci5wcml2aWxlZ2UuUmVzb3VyY2VCYWdEaXN0cmlidXRlRGV0YWlsSABC",
            "CAoGZGV0YWlsIs0DChlSZXNvdXJjZUJhZ0FsbG9jYXRlRGV0YWlsEhAKCGV2",
            "ZW50X2lkGAEgASgJEhkKEWFsbG9jYXRlX2F1ZGl0X2lkGAIgASgDEhsKE3Jl",
            "c291cmNlX3BhY2thZ2VfaWQYAyABKAMSIgoacmVzb3VyY2VfcGFja2FnZV9k",
            "ZXRhaWxfaWQYBCABKAMSFwoPcmVzb3VyY2VfYmFnX2lkGAUgASgDEjwKC3Rh",
            "cmdldF90eXBlGAYgASgOMicuYXBpLnByaXZpbGVnZS52Mi5SZXNvdXJjZUJh",
            "Z1RhcmdldFR5cGUSEQoJdGFyZ2V0X2lkGAcgASgDEjUKDXJlc291cmNlX3R5",
            "cGUYCCABKA4yHi5hcGkucHJpdmlsZWdlLnYyLlJlc291cmNlVHlwZRITCgty",
            "ZXNvdXJjZV9pZBgJIAEoAxIxCgtlZmZlY3RfdHlwZRgbIAEoDjIcLmFwaS5w",
            "cml2aWxlZ2UudjIuRWZmZWN0VHlwZRIQCghxdWFudGl0eRgKIAEoAxIWCg5l",
            "ZmZlY3RpdmVfdGltZRgLIAEoAxIbChNkaXN0cmlidXRlX2RlYWRsaW5lGAwg",
            "ASgDEhIKCmNyZWF0ZWRfYXQYDSABKAMi4wMKG1Jlc291cmNlQmFnRGlzdHJp",
            "YnV0ZURldGFpbBIQCghldmVudF9pZBgBIAEoCRIXCg9yZXNvdXJjZV9iYWdf",
            "aWQYAiABKAMSIgoacmVzb3VyY2VfcGFja2FnZV9kZXRhaWxfaWQYAyABKAMS",
            "GQoRZGlzdHJpYnV0ZV9sb2dfaWQYBCABKAMSPAoLdGFyZ2V0X3R5cGUYBSAB",
            "KA4yJy5hcGkucHJpdmlsZWdlLnYyLlJlc291cmNlQmFnVGFyZ2V0VHlwZRIR",
            "Cgl0YXJnZXRfaWQYBiABKAMSFgoOZGlzdHJpYnV0ZV91aWQYByABKAMSEwoL",
            "cmVjZWl2ZV91aWQYCCABKAMSNQoNcmVzb3VyY2VfdHlwZRgJIAEoDjIeLmFw",
            "aS5wcml2aWxlZ2UudjIuUmVzb3VyY2VUeXBlEhMKC3Jlc291cmNlX2lkGAog",
            "ASgDEjEKC2VmZmVjdF90eXBlGBsgASgOMhwuYXBpLnByaXZpbGVnZS52Mi5F",
            "ZmZlY3RUeXBlEhAKCHF1YW50aXR5GAsgASgDEhYKDmVmZmVjdGl2ZV90aW1l",
            "GAwgASgDEh4KFmFjdHVhbF9kaXN0cmlidXRlX3RpbWUYDSABKAMSEwoLZXhw",
            "aXJlX3RpbWUYDiABKAMqhgEKFFJlc291cmNlQmFnRXZlbnRUeXBlEiAKHFJF",
            "U09VUkNFX0JBR19FVkVOVF9UWVBFX05PTkUQABIkCiBSRVNPVVJDRV9CQUdf",
            "RVZFTlRfVFlQRV9BTExPQ0FURRABEiYKIlJFU09VUkNFX0JBR19FVkVOVF9U",
            "WVBFX0RJU1RSSUJVVEUQAkIzWjFnaXRpdC5jYy9zb2NpYWwvcHJvdG9idWYv",
            "Z2VuY29kZS9zdnIvcGJzcHJpdmlsZWdlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Api.Privilege.V2.ResourceBagReflection.Descriptor, global::Api.Privilege.V2.ResourcePackageReflection.Descriptor, global::Api.Privilege.V2.PrivilegeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Svr.Privilege.ResourceBagEventType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Svr.Privilege.ResourceBagEvent), global::Svr.Privilege.ResourceBagEvent.Parser, new[]{ "Anm", "SubAnm", "EventTime", "EventType", "Details" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Svr.Privilege.ResourceBagEventDetail), global::Svr.Privilege.ResourceBagEventDetail.Parser, new[]{ "Allocate", "Distribute" }, new[]{ "Detail" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Svr.Privilege.ResourceBagAllocateDetail), global::Svr.Privilege.ResourceBagAllocateDetail.Parser, new[]{ "EventId", "AllocateAuditId", "ResourcePackageId", "ResourcePackageDetailId", "ResourceBagId", "TargetType", "TargetId", "ResourceType", "ResourceId", "EffectType", "Quantity", "EffectiveTime", "DistributeDeadline", "CreatedAt" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Svr.Privilege.ResourceBagDistributeDetail), global::Svr.Privilege.ResourceBagDistributeDetail.Parser, new[]{ "EventId", "ResourceBagId", "ResourcePackageDetailId", "DistributeLogId", "TargetType", "TargetId", "DistributeUid", "ReceiveUid", "ResourceType", "ResourceId", "EffectType", "Quantity", "EffectiveTime", "ActualDistributeTime", "ExpireTime" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 操作类型枚举
  /// </summary>
  public enum ResourceBagEventType {
    /// <summary>
    /// 无意义
    /// </summary>
    [pbr::OriginalName("RESOURCE_BAG_EVENT_TYPE_NONE")] None = 0,
    /// <summary>
    /// 资源背包分配(运营→家族/特权用户)
    /// </summary>
    [pbr::OriginalName("RESOURCE_BAG_EVENT_TYPE_ALLOCATE")] Allocate = 1,
    /// <summary>
    /// 资源背包发放(家族/特权用户→普通用户)
    /// </summary>
    [pbr::OriginalName("RESOURCE_BAG_EVENT_TYPE_DISTRIBUTE")] Distribute = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  /// 资源背包事件
  /// Kafka-Topic: social-privilege-resource-bag-event-${anm}
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ResourceBagEvent : pb::IMessage<ResourceBagEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResourceBagEvent> _parser = new pb::MessageParser<ResourceBagEvent>(() => new ResourceBagEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ResourceBagEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Svr.Privilege.ResourceBagMqReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceBagEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceBagEvent(ResourceBagEvent other) : this() {
      anm_ = other.anm_;
      subAnm_ = other.subAnm_;
      eventTime_ = other.eventTime_;
      eventType_ = other.eventType_;
      details_ = other.details_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceBagEvent Clone() {
      return new ResourceBagEvent(this);
    }

    /// <summary>Field number for the "anm" field.</summary>
    public const int AnmFieldNumber = 1;
    private string anm_ = "";
    /// <summary>
    /// 业务名
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Anm {
      get { return anm_; }
      set {
        anm_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sub_anm" field.</summary>
    public const int SubAnmFieldNumber = 2;
    private string subAnm_ = "";
    /// <summary>
    /// 子业务
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SubAnm {
      get { return subAnm_; }
      set {
        subAnm_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "event_time" field.</summary>
    public const int EventTimeFieldNumber = 3;
    private long eventTime_;
    /// <summary>
    /// 事件发生时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long EventTime {
      get { return eventTime_; }
      set {
        eventTime_ = value;
      }
    }

    /// <summary>Field number for the "event_type" field.</summary>
    public const int EventTypeFieldNumber = 4;
    private global::Svr.Privilege.ResourceBagEventType eventType_ = global::Svr.Privilege.ResourceBagEventType.None;
    /// <summary>
    /// 事件类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Svr.Privilege.ResourceBagEventType EventType {
      get { return eventType_; }
      set {
        eventType_ = value;
      }
    }

    /// <summary>Field number for the "details" field.</summary>
    public const int DetailsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Svr.Privilege.ResourceBagEventDetail> _repeated_details_codec
        = pb::FieldCodec.ForMessage(42, global::Svr.Privilege.ResourceBagEventDetail.Parser);
    private readonly pbc::RepeatedField<global::Svr.Privilege.ResourceBagEventDetail> details_ = new pbc::RepeatedField<global::Svr.Privilege.ResourceBagEventDetail>();
    /// <summary>
    /// 事件明细列表(根据event_type选择结构)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Svr.Privilege.ResourceBagEventDetail> Details {
      get { return details_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ResourceBagEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ResourceBagEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Anm != other.Anm) return false;
      if (SubAnm != other.SubAnm) return false;
      if (EventTime != other.EventTime) return false;
      if (EventType != other.EventType) return false;
      if(!details_.Equals(other.details_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Anm.Length != 0) hash ^= Anm.GetHashCode();
      if (SubAnm.Length != 0) hash ^= SubAnm.GetHashCode();
      if (EventTime != 0L) hash ^= EventTime.GetHashCode();
      if (EventType != global::Svr.Privilege.ResourceBagEventType.None) hash ^= EventType.GetHashCode();
      hash ^= details_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Anm.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Anm);
      }
      if (SubAnm.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SubAnm);
      }
      if (EventTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(EventTime);
      }
      if (EventType != global::Svr.Privilege.ResourceBagEventType.None) {
        output.WriteRawTag(32);
        output.WriteEnum((int) EventType);
      }
      details_.WriteTo(output, _repeated_details_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Anm.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Anm);
      }
      if (SubAnm.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SubAnm);
      }
      if (EventTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(EventTime);
      }
      if (EventType != global::Svr.Privilege.ResourceBagEventType.None) {
        output.WriteRawTag(32);
        output.WriteEnum((int) EventType);
      }
      details_.WriteTo(ref output, _repeated_details_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Anm.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Anm);
      }
      if (SubAnm.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SubAnm);
      }
      if (EventTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(EventTime);
      }
      if (EventType != global::Svr.Privilege.ResourceBagEventType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EventType);
      }
      size += details_.CalculateSize(_repeated_details_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ResourceBagEvent other) {
      if (other == null) {
        return;
      }
      if (other.Anm.Length != 0) {
        Anm = other.Anm;
      }
      if (other.SubAnm.Length != 0) {
        SubAnm = other.SubAnm;
      }
      if (other.EventTime != 0L) {
        EventTime = other.EventTime;
      }
      if (other.EventType != global::Svr.Privilege.ResourceBagEventType.None) {
        EventType = other.EventType;
      }
      details_.Add(other.details_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Anm = input.ReadString();
            break;
          }
          case 18: {
            SubAnm = input.ReadString();
            break;
          }
          case 24: {
            EventTime = input.ReadInt64();
            break;
          }
          case 32: {
            EventType = (global::Svr.Privilege.ResourceBagEventType) input.ReadEnum();
            break;
          }
          case 42: {
            details_.AddEntriesFrom(input, _repeated_details_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Anm = input.ReadString();
            break;
          }
          case 18: {
            SubAnm = input.ReadString();
            break;
          }
          case 24: {
            EventTime = input.ReadInt64();
            break;
          }
          case 32: {
            EventType = (global::Svr.Privilege.ResourceBagEventType) input.ReadEnum();
            break;
          }
          case 42: {
            details_.AddEntriesFrom(ref input, _repeated_details_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 单条操作明细
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ResourceBagEventDetail : pb::IMessage<ResourceBagEventDetail>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResourceBagEventDetail> _parser = new pb::MessageParser<ResourceBagEventDetail>(() => new ResourceBagEventDetail());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ResourceBagEventDetail> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Svr.Privilege.ResourceBagMqReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceBagEventDetail() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceBagEventDetail(ResourceBagEventDetail other) : this() {
      switch (other.DetailCase) {
        case DetailOneofCase.Allocate:
          Allocate = other.Allocate.Clone();
          break;
        case DetailOneofCase.Distribute:
          Distribute = other.Distribute.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceBagEventDetail Clone() {
      return new ResourceBagEventDetail(this);
    }

    /// <summary>Field number for the "allocate" field.</summary>
    public const int AllocateFieldNumber = 1;
    /// <summary>
    /// 分配明细
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Svr.Privilege.ResourceBagAllocateDetail Allocate {
      get { return detailCase_ == DetailOneofCase.Allocate ? (global::Svr.Privilege.ResourceBagAllocateDetail) detail_ : null; }
      set {
        detail_ = value;
        detailCase_ = value == null ? DetailOneofCase.None : DetailOneofCase.Allocate;
      }
    }

    /// <summary>Field number for the "distribute" field.</summary>
    public const int DistributeFieldNumber = 2;
    /// <summary>
    /// 发放明细
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Svr.Privilege.ResourceBagDistributeDetail Distribute {
      get { return detailCase_ == DetailOneofCase.Distribute ? (global::Svr.Privilege.ResourceBagDistributeDetail) detail_ : null; }
      set {
        detail_ = value;
        detailCase_ = value == null ? DetailOneofCase.None : DetailOneofCase.Distribute;
      }
    }

    private object detail_;
    /// <summary>Enum of possible cases for the "detail" oneof.</summary>
    public enum DetailOneofCase {
      None = 0,
      Allocate = 1,
      Distribute = 2,
    }
    private DetailOneofCase detailCase_ = DetailOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DetailOneofCase DetailCase {
      get { return detailCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDetail() {
      detailCase_ = DetailOneofCase.None;
      detail_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ResourceBagEventDetail);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ResourceBagEventDetail other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Allocate, other.Allocate)) return false;
      if (!object.Equals(Distribute, other.Distribute)) return false;
      if (DetailCase != other.DetailCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (detailCase_ == DetailOneofCase.Allocate) hash ^= Allocate.GetHashCode();
      if (detailCase_ == DetailOneofCase.Distribute) hash ^= Distribute.GetHashCode();
      hash ^= (int) detailCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (detailCase_ == DetailOneofCase.Allocate) {
        output.WriteRawTag(10);
        output.WriteMessage(Allocate);
      }
      if (detailCase_ == DetailOneofCase.Distribute) {
        output.WriteRawTag(18);
        output.WriteMessage(Distribute);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (detailCase_ == DetailOneofCase.Allocate) {
        output.WriteRawTag(10);
        output.WriteMessage(Allocate);
      }
      if (detailCase_ == DetailOneofCase.Distribute) {
        output.WriteRawTag(18);
        output.WriteMessage(Distribute);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (detailCase_ == DetailOneofCase.Allocate) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Allocate);
      }
      if (detailCase_ == DetailOneofCase.Distribute) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Distribute);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ResourceBagEventDetail other) {
      if (other == null) {
        return;
      }
      switch (other.DetailCase) {
        case DetailOneofCase.Allocate:
          if (Allocate == null) {
            Allocate = new global::Svr.Privilege.ResourceBagAllocateDetail();
          }
          Allocate.MergeFrom(other.Allocate);
          break;
        case DetailOneofCase.Distribute:
          if (Distribute == null) {
            Distribute = new global::Svr.Privilege.ResourceBagDistributeDetail();
          }
          Distribute.MergeFrom(other.Distribute);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Svr.Privilege.ResourceBagAllocateDetail subBuilder = new global::Svr.Privilege.ResourceBagAllocateDetail();
            if (detailCase_ == DetailOneofCase.Allocate) {
              subBuilder.MergeFrom(Allocate);
            }
            input.ReadMessage(subBuilder);
            Allocate = subBuilder;
            break;
          }
          case 18: {
            global::Svr.Privilege.ResourceBagDistributeDetail subBuilder = new global::Svr.Privilege.ResourceBagDistributeDetail();
            if (detailCase_ == DetailOneofCase.Distribute) {
              subBuilder.MergeFrom(Distribute);
            }
            input.ReadMessage(subBuilder);
            Distribute = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Svr.Privilege.ResourceBagAllocateDetail subBuilder = new global::Svr.Privilege.ResourceBagAllocateDetail();
            if (detailCase_ == DetailOneofCase.Allocate) {
              subBuilder.MergeFrom(Allocate);
            }
            input.ReadMessage(subBuilder);
            Allocate = subBuilder;
            break;
          }
          case 18: {
            global::Svr.Privilege.ResourceBagDistributeDetail subBuilder = new global::Svr.Privilege.ResourceBagDistributeDetail();
            if (detailCase_ == DetailOneofCase.Distribute) {
              subBuilder.MergeFrom(Distribute);
            }
            input.ReadMessage(subBuilder);
            Distribute = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 资源背包分配详情
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ResourceBagAllocateDetail : pb::IMessage<ResourceBagAllocateDetail>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResourceBagAllocateDetail> _parser = new pb::MessageParser<ResourceBagAllocateDetail>(() => new ResourceBagAllocateDetail());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ResourceBagAllocateDetail> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Svr.Privilege.ResourceBagMqReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceBagAllocateDetail() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceBagAllocateDetail(ResourceBagAllocateDetail other) : this() {
      eventId_ = other.eventId_;
      allocateAuditId_ = other.allocateAuditId_;
      resourcePackageId_ = other.resourcePackageId_;
      resourcePackageDetailId_ = other.resourcePackageDetailId_;
      resourceBagId_ = other.resourceBagId_;
      targetType_ = other.targetType_;
      targetId_ = other.targetId_;
      resourceType_ = other.resourceType_;
      resourceId_ = other.resourceId_;
      effectType_ = other.effectType_;
      quantity_ = other.quantity_;
      effectiveTime_ = other.effectiveTime_;
      distributeDeadline_ = other.distributeDeadline_;
      createdAt_ = other.createdAt_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceBagAllocateDetail Clone() {
      return new ResourceBagAllocateDetail(this);
    }

    /// <summary>Field number for the "event_id" field.</summary>
    public const int EventIdFieldNumber = 1;
    private string eventId_ = "";
    /// <summary>
    /// 事件唯一ID(幂等)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EventId {
      get { return eventId_; }
      set {
        eventId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "allocate_audit_id" field.</summary>
    public const int AllocateAuditIdFieldNumber = 2;
    private long allocateAuditId_;
    /// <summary>
    /// 审核记录ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AllocateAuditId {
      get { return allocateAuditId_; }
      set {
        allocateAuditId_ = value;
      }
    }

    /// <summary>Field number for the "resource_package_id" field.</summary>
    public const int ResourcePackageIdFieldNumber = 3;
    private long resourcePackageId_;
    /// <summary>
    /// 资源包ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ResourcePackageId {
      get { return resourcePackageId_; }
      set {
        resourcePackageId_ = value;
      }
    }

    /// <summary>Field number for the "resource_package_detail_id" field.</summary>
    public const int ResourcePackageDetailIdFieldNumber = 4;
    private long resourcePackageDetailId_;
    /// <summary>
    /// 资源包详情id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ResourcePackageDetailId {
      get { return resourcePackageDetailId_; }
      set {
        resourcePackageDetailId_ = value;
      }
    }

    /// <summary>Field number for the "resource_bag_id" field.</summary>
    public const int ResourceBagIdFieldNumber = 5;
    private long resourceBagId_;
    /// <summary>
    /// 资源背包ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ResourceBagId {
      get { return resourceBagId_; }
      set {
        resourceBagId_ = value;
      }
    }

    /// <summary>Field number for the "target_type" field.</summary>
    public const int TargetTypeFieldNumber = 6;
    private global::Api.Privilege.V2.ResourceBagTargetType targetType_ = global::Api.Privilege.V2.ResourceBagTargetType.None;
    /// <summary>
    /// 拥有者类型(1:用户,2:家族)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Privilege.V2.ResourceBagTargetType TargetType {
      get { return targetType_; }
      set {
        targetType_ = value;
      }
    }

    /// <summary>Field number for the "target_id" field.</summary>
    public const int TargetIdFieldNumber = 7;
    private long targetId_;
    /// <summary>
    /// 拥有者Id(uid/family_id)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TargetId {
      get { return targetId_; }
      set {
        targetId_ = value;
      }
    }

    /// <summary>Field number for the "resource_type" field.</summary>
    public const int ResourceTypeFieldNumber = 8;
    private global::Api.Privilege.V2.ResourceType resourceType_ = global::Api.Privilege.V2.ResourceType.None;
    /// <summary>
    /// 资源类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Privilege.V2.ResourceType ResourceType {
      get { return resourceType_; }
      set {
        resourceType_ = value;
      }
    }

    /// <summary>Field number for the "resource_id" field.</summary>
    public const int ResourceIdFieldNumber = 9;
    private long resourceId_;
    /// <summary>
    /// 资源id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ResourceId {
      get { return resourceId_; }
      set {
        resourceId_ = value;
      }
    }

    /// <summary>Field number for the "effect_type" field.</summary>
    public const int EffectTypeFieldNumber = 27;
    private global::Api.Privilege.V2.EffectType effectType_ = global::Api.Privilege.V2.EffectType.None;
    /// <summary>
    /// 生效类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Privilege.V2.EffectType EffectType {
      get { return effectType_; }
      set {
        effectType_ = value;
      }
    }

    /// <summary>Field number for the "quantity" field.</summary>
    public const int QuantityFieldNumber = 10;
    private long quantity_;
    /// <summary>
    /// 资源数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Quantity {
      get { return quantity_; }
      set {
        quantity_ = value;
      }
    }

    /// <summary>Field number for the "effective_time" field.</summary>
    public const int EffectiveTimeFieldNumber = 11;
    private long effectiveTime_;
    /// <summary>
    /// 有效时间(单位:秒,值&lt;=0:永久)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long EffectiveTime {
      get { return effectiveTime_; }
      set {
        effectiveTime_ = value;
      }
    }

    /// <summary>Field number for the "distribute_deadline" field.</summary>
    public const int DistributeDeadlineFieldNumber = 12;
    private long distributeDeadline_;
    /// <summary>
    /// 资源发放截止时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long DistributeDeadline {
      get { return distributeDeadline_; }
      set {
        distributeDeadline_ = value;
      }
    }

    /// <summary>Field number for the "created_at" field.</summary>
    public const int CreatedAtFieldNumber = 13;
    private long createdAt_;
    /// <summary>
    /// 创建时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CreatedAt {
      get { return createdAt_; }
      set {
        createdAt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ResourceBagAllocateDetail);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ResourceBagAllocateDetail other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EventId != other.EventId) return false;
      if (AllocateAuditId != other.AllocateAuditId) return false;
      if (ResourcePackageId != other.ResourcePackageId) return false;
      if (ResourcePackageDetailId != other.ResourcePackageDetailId) return false;
      if (ResourceBagId != other.ResourceBagId) return false;
      if (TargetType != other.TargetType) return false;
      if (TargetId != other.TargetId) return false;
      if (ResourceType != other.ResourceType) return false;
      if (ResourceId != other.ResourceId) return false;
      if (EffectType != other.EffectType) return false;
      if (Quantity != other.Quantity) return false;
      if (EffectiveTime != other.EffectiveTime) return false;
      if (DistributeDeadline != other.DistributeDeadline) return false;
      if (CreatedAt != other.CreatedAt) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EventId.Length != 0) hash ^= EventId.GetHashCode();
      if (AllocateAuditId != 0L) hash ^= AllocateAuditId.GetHashCode();
      if (ResourcePackageId != 0L) hash ^= ResourcePackageId.GetHashCode();
      if (ResourcePackageDetailId != 0L) hash ^= ResourcePackageDetailId.GetHashCode();
      if (ResourceBagId != 0L) hash ^= ResourceBagId.GetHashCode();
      if (TargetType != global::Api.Privilege.V2.ResourceBagTargetType.None) hash ^= TargetType.GetHashCode();
      if (TargetId != 0L) hash ^= TargetId.GetHashCode();
      if (ResourceType != global::Api.Privilege.V2.ResourceType.None) hash ^= ResourceType.GetHashCode();
      if (ResourceId != 0L) hash ^= ResourceId.GetHashCode();
      if (EffectType != global::Api.Privilege.V2.EffectType.None) hash ^= EffectType.GetHashCode();
      if (Quantity != 0L) hash ^= Quantity.GetHashCode();
      if (EffectiveTime != 0L) hash ^= EffectiveTime.GetHashCode();
      if (DistributeDeadline != 0L) hash ^= DistributeDeadline.GetHashCode();
      if (CreatedAt != 0L) hash ^= CreatedAt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EventId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EventId);
      }
      if (AllocateAuditId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(AllocateAuditId);
      }
      if (ResourcePackageId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(ResourcePackageId);
      }
      if (ResourcePackageDetailId != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(ResourcePackageDetailId);
      }
      if (ResourceBagId != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(ResourceBagId);
      }
      if (TargetType != global::Api.Privilege.V2.ResourceBagTargetType.None) {
        output.WriteRawTag(48);
        output.WriteEnum((int) TargetType);
      }
      if (TargetId != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(TargetId);
      }
      if (ResourceType != global::Api.Privilege.V2.ResourceType.None) {
        output.WriteRawTag(64);
        output.WriteEnum((int) ResourceType);
      }
      if (ResourceId != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(ResourceId);
      }
      if (Quantity != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(Quantity);
      }
      if (EffectiveTime != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(EffectiveTime);
      }
      if (DistributeDeadline != 0L) {
        output.WriteRawTag(96);
        output.WriteInt64(DistributeDeadline);
      }
      if (CreatedAt != 0L) {
        output.WriteRawTag(104);
        output.WriteInt64(CreatedAt);
      }
      if (EffectType != global::Api.Privilege.V2.EffectType.None) {
        output.WriteRawTag(216, 1);
        output.WriteEnum((int) EffectType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EventId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EventId);
      }
      if (AllocateAuditId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(AllocateAuditId);
      }
      if (ResourcePackageId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(ResourcePackageId);
      }
      if (ResourcePackageDetailId != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(ResourcePackageDetailId);
      }
      if (ResourceBagId != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(ResourceBagId);
      }
      if (TargetType != global::Api.Privilege.V2.ResourceBagTargetType.None) {
        output.WriteRawTag(48);
        output.WriteEnum((int) TargetType);
      }
      if (TargetId != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(TargetId);
      }
      if (ResourceType != global::Api.Privilege.V2.ResourceType.None) {
        output.WriteRawTag(64);
        output.WriteEnum((int) ResourceType);
      }
      if (ResourceId != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(ResourceId);
      }
      if (Quantity != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(Quantity);
      }
      if (EffectiveTime != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(EffectiveTime);
      }
      if (DistributeDeadline != 0L) {
        output.WriteRawTag(96);
        output.WriteInt64(DistributeDeadline);
      }
      if (CreatedAt != 0L) {
        output.WriteRawTag(104);
        output.WriteInt64(CreatedAt);
      }
      if (EffectType != global::Api.Privilege.V2.EffectType.None) {
        output.WriteRawTag(216, 1);
        output.WriteEnum((int) EffectType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EventId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EventId);
      }
      if (AllocateAuditId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AllocateAuditId);
      }
      if (ResourcePackageId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ResourcePackageId);
      }
      if (ResourcePackageDetailId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ResourcePackageDetailId);
      }
      if (ResourceBagId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ResourceBagId);
      }
      if (TargetType != global::Api.Privilege.V2.ResourceBagTargetType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TargetType);
      }
      if (TargetId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TargetId);
      }
      if (ResourceType != global::Api.Privilege.V2.ResourceType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ResourceType);
      }
      if (ResourceId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ResourceId);
      }
      if (EffectType != global::Api.Privilege.V2.EffectType.None) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) EffectType);
      }
      if (Quantity != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Quantity);
      }
      if (EffectiveTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(EffectiveTime);
      }
      if (DistributeDeadline != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(DistributeDeadline);
      }
      if (CreatedAt != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CreatedAt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ResourceBagAllocateDetail other) {
      if (other == null) {
        return;
      }
      if (other.EventId.Length != 0) {
        EventId = other.EventId;
      }
      if (other.AllocateAuditId != 0L) {
        AllocateAuditId = other.AllocateAuditId;
      }
      if (other.ResourcePackageId != 0L) {
        ResourcePackageId = other.ResourcePackageId;
      }
      if (other.ResourcePackageDetailId != 0L) {
        ResourcePackageDetailId = other.ResourcePackageDetailId;
      }
      if (other.ResourceBagId != 0L) {
        ResourceBagId = other.ResourceBagId;
      }
      if (other.TargetType != global::Api.Privilege.V2.ResourceBagTargetType.None) {
        TargetType = other.TargetType;
      }
      if (other.TargetId != 0L) {
        TargetId = other.TargetId;
      }
      if (other.ResourceType != global::Api.Privilege.V2.ResourceType.None) {
        ResourceType = other.ResourceType;
      }
      if (other.ResourceId != 0L) {
        ResourceId = other.ResourceId;
      }
      if (other.EffectType != global::Api.Privilege.V2.EffectType.None) {
        EffectType = other.EffectType;
      }
      if (other.Quantity != 0L) {
        Quantity = other.Quantity;
      }
      if (other.EffectiveTime != 0L) {
        EffectiveTime = other.EffectiveTime;
      }
      if (other.DistributeDeadline != 0L) {
        DistributeDeadline = other.DistributeDeadline;
      }
      if (other.CreatedAt != 0L) {
        CreatedAt = other.CreatedAt;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            EventId = input.ReadString();
            break;
          }
          case 16: {
            AllocateAuditId = input.ReadInt64();
            break;
          }
          case 24: {
            ResourcePackageId = input.ReadInt64();
            break;
          }
          case 32: {
            ResourcePackageDetailId = input.ReadInt64();
            break;
          }
          case 40: {
            ResourceBagId = input.ReadInt64();
            break;
          }
          case 48: {
            TargetType = (global::Api.Privilege.V2.ResourceBagTargetType) input.ReadEnum();
            break;
          }
          case 56: {
            TargetId = input.ReadInt64();
            break;
          }
          case 64: {
            ResourceType = (global::Api.Privilege.V2.ResourceType) input.ReadEnum();
            break;
          }
          case 72: {
            ResourceId = input.ReadInt64();
            break;
          }
          case 80: {
            Quantity = input.ReadInt64();
            break;
          }
          case 88: {
            EffectiveTime = input.ReadInt64();
            break;
          }
          case 96: {
            DistributeDeadline = input.ReadInt64();
            break;
          }
          case 104: {
            CreatedAt = input.ReadInt64();
            break;
          }
          case 216: {
            EffectType = (global::Api.Privilege.V2.EffectType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            EventId = input.ReadString();
            break;
          }
          case 16: {
            AllocateAuditId = input.ReadInt64();
            break;
          }
          case 24: {
            ResourcePackageId = input.ReadInt64();
            break;
          }
          case 32: {
            ResourcePackageDetailId = input.ReadInt64();
            break;
          }
          case 40: {
            ResourceBagId = input.ReadInt64();
            break;
          }
          case 48: {
            TargetType = (global::Api.Privilege.V2.ResourceBagTargetType) input.ReadEnum();
            break;
          }
          case 56: {
            TargetId = input.ReadInt64();
            break;
          }
          case 64: {
            ResourceType = (global::Api.Privilege.V2.ResourceType) input.ReadEnum();
            break;
          }
          case 72: {
            ResourceId = input.ReadInt64();
            break;
          }
          case 80: {
            Quantity = input.ReadInt64();
            break;
          }
          case 88: {
            EffectiveTime = input.ReadInt64();
            break;
          }
          case 96: {
            DistributeDeadline = input.ReadInt64();
            break;
          }
          case 104: {
            CreatedAt = input.ReadInt64();
            break;
          }
          case 216: {
            EffectType = (global::Api.Privilege.V2.EffectType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 资源背包发放明细
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ResourceBagDistributeDetail : pb::IMessage<ResourceBagDistributeDetail>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResourceBagDistributeDetail> _parser = new pb::MessageParser<ResourceBagDistributeDetail>(() => new ResourceBagDistributeDetail());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ResourceBagDistributeDetail> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Svr.Privilege.ResourceBagMqReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceBagDistributeDetail() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceBagDistributeDetail(ResourceBagDistributeDetail other) : this() {
      eventId_ = other.eventId_;
      resourceBagId_ = other.resourceBagId_;
      resourcePackageDetailId_ = other.resourcePackageDetailId_;
      distributeLogId_ = other.distributeLogId_;
      targetType_ = other.targetType_;
      targetId_ = other.targetId_;
      distributeUid_ = other.distributeUid_;
      receiveUid_ = other.receiveUid_;
      resourceType_ = other.resourceType_;
      resourceId_ = other.resourceId_;
      effectType_ = other.effectType_;
      quantity_ = other.quantity_;
      effectiveTime_ = other.effectiveTime_;
      actualDistributeTime_ = other.actualDistributeTime_;
      expireTime_ = other.expireTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceBagDistributeDetail Clone() {
      return new ResourceBagDistributeDetail(this);
    }

    /// <summary>Field number for the "event_id" field.</summary>
    public const int EventIdFieldNumber = 1;
    private string eventId_ = "";
    /// <summary>
    /// 事件唯一ID(幂等)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EventId {
      get { return eventId_; }
      set {
        eventId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "resource_bag_id" field.</summary>
    public const int ResourceBagIdFieldNumber = 2;
    private long resourceBagId_;
    /// <summary>
    /// 特权资源背包id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ResourceBagId {
      get { return resourceBagId_; }
      set {
        resourceBagId_ = value;
      }
    }

    /// <summary>Field number for the "resource_package_detail_id" field.</summary>
    public const int ResourcePackageDetailIdFieldNumber = 3;
    private long resourcePackageDetailId_;
    /// <summary>
    /// 资源包详情id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ResourcePackageDetailId {
      get { return resourcePackageDetailId_; }
      set {
        resourcePackageDetailId_ = value;
      }
    }

    /// <summary>Field number for the "distribute_log_id" field.</summary>
    public const int DistributeLogIdFieldNumber = 4;
    private long distributeLogId_;
    /// <summary>
    /// 发放日志ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long DistributeLogId {
      get { return distributeLogId_; }
      set {
        distributeLogId_ = value;
      }
    }

    /// <summary>Field number for the "target_type" field.</summary>
    public const int TargetTypeFieldNumber = 5;
    private global::Api.Privilege.V2.ResourceBagTargetType targetType_ = global::Api.Privilege.V2.ResourceBagTargetType.None;
    /// <summary>
    /// 拥有者类型(1:用户,2:家族)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Privilege.V2.ResourceBagTargetType TargetType {
      get { return targetType_; }
      set {
        targetType_ = value;
      }
    }

    /// <summary>Field number for the "target_id" field.</summary>
    public const int TargetIdFieldNumber = 6;
    private long targetId_;
    /// <summary>
    /// 拥有者Id(uid/family_id)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TargetId {
      get { return targetId_; }
      set {
        targetId_ = value;
      }
    }

    /// <summary>Field number for the "distribute_uid" field.</summary>
    public const int DistributeUidFieldNumber = 7;
    private long distributeUid_;
    /// <summary>
    /// 发放资源用户ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long DistributeUid {
      get { return distributeUid_; }
      set {
        distributeUid_ = value;
      }
    }

    /// <summary>Field number for the "receive_uid" field.</summary>
    public const int ReceiveUidFieldNumber = 8;
    private long receiveUid_;
    /// <summary>
    /// 接收资源用户ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ReceiveUid {
      get { return receiveUid_; }
      set {
        receiveUid_ = value;
      }
    }

    /// <summary>Field number for the "resource_type" field.</summary>
    public const int ResourceTypeFieldNumber = 9;
    private global::Api.Privilege.V2.ResourceType resourceType_ = global::Api.Privilege.V2.ResourceType.None;
    /// <summary>
    /// 资源类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Privilege.V2.ResourceType ResourceType {
      get { return resourceType_; }
      set {
        resourceType_ = value;
      }
    }

    /// <summary>Field number for the "resource_id" field.</summary>
    public const int ResourceIdFieldNumber = 10;
    private long resourceId_;
    /// <summary>
    /// 资源id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ResourceId {
      get { return resourceId_; }
      set {
        resourceId_ = value;
      }
    }

    /// <summary>Field number for the "effect_type" field.</summary>
    public const int EffectTypeFieldNumber = 27;
    private global::Api.Privilege.V2.EffectType effectType_ = global::Api.Privilege.V2.EffectType.None;
    /// <summary>
    /// 生效类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Privilege.V2.EffectType EffectType {
      get { return effectType_; }
      set {
        effectType_ = value;
      }
    }

    /// <summary>Field number for the "quantity" field.</summary>
    public const int QuantityFieldNumber = 11;
    private long quantity_;
    /// <summary>
    /// 资源发放数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Quantity {
      get { return quantity_; }
      set {
        quantity_ = value;
      }
    }

    /// <summary>Field number for the "effective_time" field.</summary>
    public const int EffectiveTimeFieldNumber = 12;
    private long effectiveTime_;
    /// <summary>
    /// 有效时间(单位:秒,值&lt;=0:永久)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long EffectiveTime {
      get { return effectiveTime_; }
      set {
        effectiveTime_ = value;
      }
    }

    /// <summary>Field number for the "actual_distribute_time" field.</summary>
    public const int ActualDistributeTimeFieldNumber = 13;
    private long actualDistributeTime_;
    /// <summary>
    /// 实际发放时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ActualDistributeTime {
      get { return actualDistributeTime_; }
      set {
        actualDistributeTime_ = value;
      }
    }

    /// <summary>Field number for the "expire_time" field.</summary>
    public const int ExpireTimeFieldNumber = 14;
    private long expireTime_;
    /// <summary>
    /// 过期时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ExpireTime {
      get { return expireTime_; }
      set {
        expireTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ResourceBagDistributeDetail);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ResourceBagDistributeDetail other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EventId != other.EventId) return false;
      if (ResourceBagId != other.ResourceBagId) return false;
      if (ResourcePackageDetailId != other.ResourcePackageDetailId) return false;
      if (DistributeLogId != other.DistributeLogId) return false;
      if (TargetType != other.TargetType) return false;
      if (TargetId != other.TargetId) return false;
      if (DistributeUid != other.DistributeUid) return false;
      if (ReceiveUid != other.ReceiveUid) return false;
      if (ResourceType != other.ResourceType) return false;
      if (ResourceId != other.ResourceId) return false;
      if (EffectType != other.EffectType) return false;
      if (Quantity != other.Quantity) return false;
      if (EffectiveTime != other.EffectiveTime) return false;
      if (ActualDistributeTime != other.ActualDistributeTime) return false;
      if (ExpireTime != other.ExpireTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EventId.Length != 0) hash ^= EventId.GetHashCode();
      if (ResourceBagId != 0L) hash ^= ResourceBagId.GetHashCode();
      if (ResourcePackageDetailId != 0L) hash ^= ResourcePackageDetailId.GetHashCode();
      if (DistributeLogId != 0L) hash ^= DistributeLogId.GetHashCode();
      if (TargetType != global::Api.Privilege.V2.ResourceBagTargetType.None) hash ^= TargetType.GetHashCode();
      if (TargetId != 0L) hash ^= TargetId.GetHashCode();
      if (DistributeUid != 0L) hash ^= DistributeUid.GetHashCode();
      if (ReceiveUid != 0L) hash ^= ReceiveUid.GetHashCode();
      if (ResourceType != global::Api.Privilege.V2.ResourceType.None) hash ^= ResourceType.GetHashCode();
      if (ResourceId != 0L) hash ^= ResourceId.GetHashCode();
      if (EffectType != global::Api.Privilege.V2.EffectType.None) hash ^= EffectType.GetHashCode();
      if (Quantity != 0L) hash ^= Quantity.GetHashCode();
      if (EffectiveTime != 0L) hash ^= EffectiveTime.GetHashCode();
      if (ActualDistributeTime != 0L) hash ^= ActualDistributeTime.GetHashCode();
      if (ExpireTime != 0L) hash ^= ExpireTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EventId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EventId);
      }
      if (ResourceBagId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ResourceBagId);
      }
      if (ResourcePackageDetailId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(ResourcePackageDetailId);
      }
      if (DistributeLogId != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(DistributeLogId);
      }
      if (TargetType != global::Api.Privilege.V2.ResourceBagTargetType.None) {
        output.WriteRawTag(40);
        output.WriteEnum((int) TargetType);
      }
      if (TargetId != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(TargetId);
      }
      if (DistributeUid != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(DistributeUid);
      }
      if (ReceiveUid != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(ReceiveUid);
      }
      if (ResourceType != global::Api.Privilege.V2.ResourceType.None) {
        output.WriteRawTag(72);
        output.WriteEnum((int) ResourceType);
      }
      if (ResourceId != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(ResourceId);
      }
      if (Quantity != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(Quantity);
      }
      if (EffectiveTime != 0L) {
        output.WriteRawTag(96);
        output.WriteInt64(EffectiveTime);
      }
      if (ActualDistributeTime != 0L) {
        output.WriteRawTag(104);
        output.WriteInt64(ActualDistributeTime);
      }
      if (ExpireTime != 0L) {
        output.WriteRawTag(112);
        output.WriteInt64(ExpireTime);
      }
      if (EffectType != global::Api.Privilege.V2.EffectType.None) {
        output.WriteRawTag(216, 1);
        output.WriteEnum((int) EffectType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EventId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EventId);
      }
      if (ResourceBagId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ResourceBagId);
      }
      if (ResourcePackageDetailId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(ResourcePackageDetailId);
      }
      if (DistributeLogId != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(DistributeLogId);
      }
      if (TargetType != global::Api.Privilege.V2.ResourceBagTargetType.None) {
        output.WriteRawTag(40);
        output.WriteEnum((int) TargetType);
      }
      if (TargetId != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(TargetId);
      }
      if (DistributeUid != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(DistributeUid);
      }
      if (ReceiveUid != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(ReceiveUid);
      }
      if (ResourceType != global::Api.Privilege.V2.ResourceType.None) {
        output.WriteRawTag(72);
        output.WriteEnum((int) ResourceType);
      }
      if (ResourceId != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(ResourceId);
      }
      if (Quantity != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(Quantity);
      }
      if (EffectiveTime != 0L) {
        output.WriteRawTag(96);
        output.WriteInt64(EffectiveTime);
      }
      if (ActualDistributeTime != 0L) {
        output.WriteRawTag(104);
        output.WriteInt64(ActualDistributeTime);
      }
      if (ExpireTime != 0L) {
        output.WriteRawTag(112);
        output.WriteInt64(ExpireTime);
      }
      if (EffectType != global::Api.Privilege.V2.EffectType.None) {
        output.WriteRawTag(216, 1);
        output.WriteEnum((int) EffectType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EventId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EventId);
      }
      if (ResourceBagId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ResourceBagId);
      }
      if (ResourcePackageDetailId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ResourcePackageDetailId);
      }
      if (DistributeLogId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(DistributeLogId);
      }
      if (TargetType != global::Api.Privilege.V2.ResourceBagTargetType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TargetType);
      }
      if (TargetId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TargetId);
      }
      if (DistributeUid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(DistributeUid);
      }
      if (ReceiveUid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ReceiveUid);
      }
      if (ResourceType != global::Api.Privilege.V2.ResourceType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ResourceType);
      }
      if (ResourceId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ResourceId);
      }
      if (EffectType != global::Api.Privilege.V2.EffectType.None) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) EffectType);
      }
      if (Quantity != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Quantity);
      }
      if (EffectiveTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(EffectiveTime);
      }
      if (ActualDistributeTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ActualDistributeTime);
      }
      if (ExpireTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ExpireTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ResourceBagDistributeDetail other) {
      if (other == null) {
        return;
      }
      if (other.EventId.Length != 0) {
        EventId = other.EventId;
      }
      if (other.ResourceBagId != 0L) {
        ResourceBagId = other.ResourceBagId;
      }
      if (other.ResourcePackageDetailId != 0L) {
        ResourcePackageDetailId = other.ResourcePackageDetailId;
      }
      if (other.DistributeLogId != 0L) {
        DistributeLogId = other.DistributeLogId;
      }
      if (other.TargetType != global::Api.Privilege.V2.ResourceBagTargetType.None) {
        TargetType = other.TargetType;
      }
      if (other.TargetId != 0L) {
        TargetId = other.TargetId;
      }
      if (other.DistributeUid != 0L) {
        DistributeUid = other.DistributeUid;
      }
      if (other.ReceiveUid != 0L) {
        ReceiveUid = other.ReceiveUid;
      }
      if (other.ResourceType != global::Api.Privilege.V2.ResourceType.None) {
        ResourceType = other.ResourceType;
      }
      if (other.ResourceId != 0L) {
        ResourceId = other.ResourceId;
      }
      if (other.EffectType != global::Api.Privilege.V2.EffectType.None) {
        EffectType = other.EffectType;
      }
      if (other.Quantity != 0L) {
        Quantity = other.Quantity;
      }
      if (other.EffectiveTime != 0L) {
        EffectiveTime = other.EffectiveTime;
      }
      if (other.ActualDistributeTime != 0L) {
        ActualDistributeTime = other.ActualDistributeTime;
      }
      if (other.ExpireTime != 0L) {
        ExpireTime = other.ExpireTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            EventId = input.ReadString();
            break;
          }
          case 16: {
            ResourceBagId = input.ReadInt64();
            break;
          }
          case 24: {
            ResourcePackageDetailId = input.ReadInt64();
            break;
          }
          case 32: {
            DistributeLogId = input.ReadInt64();
            break;
          }
          case 40: {
            TargetType = (global::Api.Privilege.V2.ResourceBagTargetType) input.ReadEnum();
            break;
          }
          case 48: {
            TargetId = input.ReadInt64();
            break;
          }
          case 56: {
            DistributeUid = input.ReadInt64();
            break;
          }
          case 64: {
            ReceiveUid = input.ReadInt64();
            break;
          }
          case 72: {
            ResourceType = (global::Api.Privilege.V2.ResourceType) input.ReadEnum();
            break;
          }
          case 80: {
            ResourceId = input.ReadInt64();
            break;
          }
          case 88: {
            Quantity = input.ReadInt64();
            break;
          }
          case 96: {
            EffectiveTime = input.ReadInt64();
            break;
          }
          case 104: {
            ActualDistributeTime = input.ReadInt64();
            break;
          }
          case 112: {
            ExpireTime = input.ReadInt64();
            break;
          }
          case 216: {
            EffectType = (global::Api.Privilege.V2.EffectType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            EventId = input.ReadString();
            break;
          }
          case 16: {
            ResourceBagId = input.ReadInt64();
            break;
          }
          case 24: {
            ResourcePackageDetailId = input.ReadInt64();
            break;
          }
          case 32: {
            DistributeLogId = input.ReadInt64();
            break;
          }
          case 40: {
            TargetType = (global::Api.Privilege.V2.ResourceBagTargetType) input.ReadEnum();
            break;
          }
          case 48: {
            TargetId = input.ReadInt64();
            break;
          }
          case 56: {
            DistributeUid = input.ReadInt64();
            break;
          }
          case 64: {
            ReceiveUid = input.ReadInt64();
            break;
          }
          case 72: {
            ResourceType = (global::Api.Privilege.V2.ResourceType) input.ReadEnum();
            break;
          }
          case 80: {
            ResourceId = input.ReadInt64();
            break;
          }
          case 88: {
            Quantity = input.ReadInt64();
            break;
          }
          case 96: {
            EffectiveTime = input.ReadInt64();
            break;
          }
          case 104: {
            ActualDistributeTime = input.ReadInt64();
            break;
          }
          case 112: {
            ExpireTime = input.ReadInt64();
            break;
          }
          case 216: {
            EffectType = (global::Api.Privilege.V2.EffectType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
